AccessKit/accesskit

- consumer/src/iterators.rs
- consumer/src/node.rs
The key insight that made this possible was the realization that `Node` could derive the `Copy` trait, which meant that `Node` methods that return other `Node`s don't need to borrow `self`.
Fixes #4
> Refactor consumer Node and iterators to reduce lookups

- consumer/src/lib.rs
- consumer/src/tree.rs
The code for processing a `TreeUpdate` can now keep track of the nodes that are added, updated, or removed, as well as a change in focus. This feature will be the basis for platform-specific events.
> Add basic tracking of the changes in a tree update

- Cargo.lock
- consumer/Cargo.toml
- consumer/src/tree.rs
This way, when a platform adapter is deriving platform-specific events from the generic changes, it has the full context for the old node as well as the new one. I expect this to be useful when determining whether platform-specific properties have changed, since some of these properties may be dependent on a node's parent or children, not just the node data itself.
To make it reasonably efficient to keep a full copy of the old tree, we now use the `im` crate's `HashMap` to provide copy-on-write behavior for the node map. It may be possible to optimize this further, but given that any waste here only affects the tree update process, it's probably not a high priority.
> Provide full versions of the old nodes in change events

- schema/src/lib.rs
I was thinking that maybe the `focus` field should contain the focused node within the tree regardless of whether the native window is focused, and the platform adapters should track the native focus. That would simplify my current toy example on Windows. But then I realized that a robust GUI toolkit needs to track the native focus anyway, so the current semantics are best. So I added documentation to clarify that.
> Clarify the semantics of `TreeUpdate::focus`

- platforms/windows/examples/hello_world.rs
- platforms/windows/src/tests/mod.rs
To see these cases in action, run the example, open the system menu (Alt+Space), choose Move or Size, then exit the move/size mode with Escape. Or open the System menu, escape out of that menu, then escape out of menu mode. In both cases, focus should not return to the button until you leave the special mode.
> Windows: Handle focus corner cases in example and tests

- consumer/src/node.rs
- platforms/windows/src/node.rs
- platforms/windows/src/util.rs
While testing with JAWS, I discovered that I need to implement the `IsControlElement`, `IsContentElement`, and `IsEnabled` properties, because JAWS doesn't respect the normal UIA-provided default values for these properties. I also refactored the abstraction for UIA properties so the getters don't all have to return an `Option`. And I modified navigation to traverse all elements, since we'll let UIA filter elements via `IsControlElement` and `IsContentElement`.
> Windows: More work on basic UIA properties and navigation

- Cargo.lock
- schema/Cargo.toml
- schema/src/lib.rs
In addition to simply being a better data type, this reduces the size of each `Node` by 40 bytes on x64.
> Use EnumSet where appropriate in the schema

- platforms/windows/examples/hello_world.rs
- platforms/windows/src/tests/mod.rs
This fixes the crash that @DataTriny reported on #37 . It has to be done in the window procedure, since that is what actually manages the lifecycle of the AccessKit manager. So we implement it in our tests and in the example, which provides a model for integrators.
> Handle WM_GETOBJECT while the window is being destroyed

- platforms/windows/examples/hello_world.rs
- platforms/windows/src/tests/mod.rs
After seeing how druid-shell handles window state, I decided it would be safer to use a const pointer plus interior mutability, in this case via `Cell`.
> Safer mutation of WindowState in Windows tests

- platforms/windows/examples/hello_world.rs
- platforms/windows/src/manager.rs
- platforms/windows/src/tests/mod.rs
This finally fixes #37. The key is to force UIA to initialize itself before we handle `WM_GETOBJECT`.
> Windows: Reliably handle all COM init scenarios on the UI thread

- Cargo.lock
- Cargo.toml
- platforms/windows/Cargo.toml
- platforms/windows/examples/hello_world.rs
- platforms/windows/src/manager.rs
- platforms/windows/src/tests/mod.rs
- provider/Cargo.toml
- provider/src/lib.rs
When integrating AccessKit with Druid, we'll need to be able to lazily initialize the accessibility tree when the first `WM_GETOBJECT` message on Windows, or equivalent request on other platforms, is received. I think this requirement will be common enough that it's worth supporting directly in AccessKit. So that's what this branch does.
I've implemented this in a backward-compatible way, so it doesn't break the tests and example, but I suppose I really should update them to lazily initialize and update the tree.
> Allow lazy initialization of trees

- provider/src/lib.rs
I need this for my integration with druid-shell. This is trivial enough that I'll go ahead and merge once CI passes.
> Make it easy to use a boxed `InitTree` implementation

- platforms/windows/examples/hello_world.rs
- platforms/windows/src/manager.rs
- platforms/windows/src/tests/mod.rs
This addresses a deadlock I encountered while working on my proof-of-concept integration with winit.
> Avoid deadlock from reentrant `WM_GETOBJECT` handling

- consumer/src/node.rs
Rust 1.57 introduced this warning, breaking CI. This fix is trivial enough that I'll merge it as soon as CI passes.
> Fix new 'redundant closure' clippy warning

- platforms/mac/examples/hello_world.rs
- platforms/mac/jni/Makefile
- platforms/mac/jni/java/dev/accesskit/mac/AccessKitMacAdapter.java
- platforms/mac/jni/src/lib.rs
- platforms/mac/src/adapter.rs
- platforms/mac/src/lib.rs
- platforms/windows/examples/hello_world.rs
- platforms/windows/src/adapter.rs
- platforms/windows/src/lib.rs
- platforms/windows/src/tests/mod.rs
I never liked "manager", but for some reason the better name escaped me while I was coding, even though I had used "adapter" in the high-level overview.
> Rename "manager" to "adapter"

- common/src/lib.rs
- consumer/src/lib.rs
- consumer/src/tree.rs
- platforms/windows/examples/hello_world.rs
- platforms/windows/src/tests/simple.rs
While working on my proof-of-concept integration with egui, I discovered that using a boxed slice for child IDs would make it inconvenient and inefficient to build up a tree as the immediate-mode GUI is being rendered. So I've gone back to using `Vec`. This does mean a small increase in the size of each `Node`, but I'll accept that tradeoff. There are other things I can do to decrease the size of each `Node`, when it's actually important to do so.
> Use `Vec` again for child IDs

- common/src/lib.rs
My proof-of-concept integration of AccessKit into [egui](https://github.com/emilk/egui) will be easier if `TreeUpdate` implements `Default`. I realized it will also be helpful to implement `Debug`.
> Derive more traits on `TreeUpdate`

- Cargo.lock
- common/Cargo.toml
- common/src/lib.rs
- consumer/src/lib.rs
- consumer/src/node.rs
- platforms/mac/src/node.rs
- platforms/windows/src/node.rs
Now we actually implement transforms, which are now decoupled from the bounding rectangle. Now that we support transforms, the old `offset_container` field of `RelativeBounds` is redundant.
We now use [kurbo](https://github.com/linebender/kurbo) rather than defining our own structures for points, rectangles, and transforms. This reduces the duplicated effort in the Rust graphics ecosystem, and gives us useful functions for manipulating these things.
I'm hoping that an updated version of kurbo with my contributed schemars support will be published to crates.io before I merge this PR.
> Refactor node transform and bounds using the kurbo crate

- common/src/lib.rs
- consumer/src/lib.rs
- consumer/src/node.rs
- consumer/src/tree.rs
- platforms/windows/examples/hello_world.rs
- platforms/windows/src/adapter.rs
- platforms/windows/src/node.rs
- platforms/windows/src/tests/mod.rs
- platforms/windows/src/tests/simple.rs
This defines a trait that providers implement to handle actions requested by assistive technologies, uses that trait to implement UIA's `SetFocus` method, and implements the trait in the Windows example.
> Handle action requests, starting with focus

- common/src/lib.rs
- consumer/src/node.rs
- platforms/windows/examples/hello_world.rs
- platforms/windows/src/node.rs
I decided to have AccessKit itself do hit testing, rather than calling back into the application.
This implementation doesn't handle all of the possible complexities of doing hit testing correctly. Known problems include transparency, cases where the z-order is different from the logical order of the children, and cases where children are clipped (e.g. a scrollable area). But I'm optimistic that we can iterate toward correct solutions to these problems. Non-rectangular bounding shapes could also be a problem, but that's quite literally a corner case. Notably, one case that this implementation already handles well is transformation of a bounding rectangle into a non-rectangular shape. Hit testing works correctly in this case because we apply the inverse transform to the point being tested. …
> Basic hit testing

- Cargo.lock
- common/src/lib.rs
- consumer/src/node.rs
- platforms/windows/Cargo.toml
- platforms/windows/src/node.rs
- platforms/windows/src/util.rs
The UIA value pattern allows access to the value of a text edit control. This will let the screen reader read the current content; full support for text editing will come later. The range value pattern is for progress bars and sliders.
As part of this work, I had to refactor the UIA implementation to use a separate struct for each pattern, to avoid method name conflicts.
> Support value and range value patterns

- Cargo.lock
I realized too late that Cargo.lock had changed when I rebuilt the Windows crate after bumping the version number. I'll also merge this once CI finishes.
> Commit new Cargo.lock from bumping the version of the Windows crate

- .github/workflows/release-please.yml
- .release-please-manifest.json
- release-please-config.json
[release-please](https://github.com/googleapis/release-please) will automatically create release PRs and maintain a changelog. This requires us to use [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) in our PR titles from now on.
> chore: Automate releases with release-please

- common/src/lib.rs
- consumer/src/lib.rs
- consumer/src/node.rs
- consumer/src/tree.rs
- platforms/windows/examples/hello_world.rs
- platforms/windows/src/tests/mod.rs
- platforms/windows/src/tests/simple.rs
I'm not sure why Chromium has this field, but I don't believe we need it.
> refactor!: Drop `TreeUpdate::clear`

- platforms/windows/examples/hello_world.rs
This reduces the time-to-onboard, by removing the need to read and
understand the example's Windows GUI logic before being able to
interact with the example.
> Print usage text to the terminal from the Windows example

- common/src/lib.rs
We're not sure what size `NodeId` should ultimately be. We may even end up making it configurable through a cargo feature. But we always want to make it easy to convert a `NonZeroU64` to a `NodeId`.
Suggested by @raphlinus.
> feat(common): Conversion from `NonZeroU64` to `NodeId`

- common/src/lib.rs
- consumer/src/lib.rs
- consumer/src/node.rs
- consumer/src/tree.rs
- platforms/windows/examples/hello_world.rs
- platforms/windows/src/tests/simple.rs
The concept of tree IDs isn't actually serving any purpose so far. It's just something I copied from Chromium. The Windows platform adapter doesn't do anything with it, and neither will any of the other platform adapters I plan to implement in the foreseeable future. I don't plan to actually implement support for child trees anytime soon. So to reduce clutter, and hopefully encourage actual adoption of AccessKit by GUI toolkits, I'm dropping this.
> refactor!: Drop unused tree IDs

- common/Cargo.toml
- consumer/Cargo.toml
- platforms/windows/Cargo.toml
Unless I missed something, updating the `Cargo.toml` files is all we need to transition to the latest edition.
I think we are better off doing it now while the codebase is still small.
> Migrate to 2021 edition

- platforms/windows/examples/winit.rs
- platforms/windows/src/lib.rs
- platforms/windows/src/subclass.rs
- platforms/windows/src/tests/subclassed.rs
Replaced `WindowSubclass` with `SubclassingAdapter`, which takes ownership of the main adapter. There's no loss of functionality though, because `SubclassingAdapter::into_inner` uninstalls the subclass and returns ownership of the main adapter. This also slightly simplifies the main winit example, and will make the main winit adapter, which must encapsulate everything in a struct, possible.
> refactor(platforms/windows)!: Refactor window subclassing to avoid lifetime issue

- common/src/lib.rs
Currently, serializing an `ActionRequest` with a `data` field set to `None` using `serde_json` gives this:
```
{"action":"default","target":2,"data":null}
```
The `data` field is useless in this case and I would need to modify some auto-generated code from JSON schema to let my program accept this kind of input.
So this PR adds the necessary `serde` attribute to the `data` field, which is inlined with what we already do in a lot of place. This one might just have been forgotten.
> Skip `ActionRequest::data` if it is `None` during serialization

- common/Cargo.toml
- common/src/lib.rs
When enabling the `schemars` feature on the `accesskit` crate, it is necessary to also enable the `serde` feature. Failing to do so will result in an invalid JSON schema being generated due to the fact that serde attributes that are applied on our types won't be present.
Here is a piece of the JSON schema that gets generated when the `serde(rename_all = "camelCase")` attribute is not applied to the `Role` enum:
```json
...
"definitions": {
"Role": {
"description": "...",
"type": "string",
"enum": [
"Unknown",
"InlineTextBox",
...
```
This PR enables the `serde` feature if the `schemars` feature is enabled, so that it is impossible to accidentally forget to enable both of them.
> Enable the serde feature when the schemars feature is turned on

- Cargo.lock
- platforms/winit/Cargo.toml
- platforms/winit/examples/simple.rs
- platforms/winit/src/platform_impl/windows.rs
Update `winit` to version `0.27.3` for the `accesskit_winit` crate.
> Bump winit dependency

- common/README.md
In the last two published versions of the crate, the README wasn't properly sent to the registry because I had set up the crate to use the top-level README via a symbolic link, but then published the crate on Windows, where (at least in my configuration) the symlink doesn't work. I could just publish this crate on Linux, as I did in previous versions, and even automate that step through CI. Ideally we should still do the latter. But I decided that this crate should have its own README, so I wrote one.
fixes #129
> fix(common): Write a README specifically for the accesskit crate

- common/src/lib.rs
- consumer/src/lib.rs
- consumer/src/node.rs
- consumer/src/tree.rs
- platforms/windows/examples/hello_world.rs
- platforms/windows/src/tests/simple.rs
- platforms/windows/src/tests/subclassed.rs
- platforms/winit/examples/simple.rs
Reasons to make this change:
* Now `Node` can derive `Default`, which makes structure initialization more standard. Note: To allow this, `Role` also derives `Default`, with a default variant of `Unknown`. But I really didn't want to make `NodeId` derive `Default`, since that would mean allowing a zero ID, and multiple nodes with zero IDs would be an invalid tree.
* In the persistent representation of the tree (in `accesskit_consumer`), the node IDs are already stored as keys in the map. So storing the IDs in the `Node` struct as well is redundant.
* In a future PR, I plan to do a much larger refactor, introducing a trait called something like `NodeProvider` that defines getter methods for all of the node fields. The `accesskit::Node` struct, which I will probably rename, will implement …
> refactor!: Store node ID in `TreeUpdate`, not `accesskit::Node`

- consumer/src/tree.rs
This is an easy fix. It removes some debug printing that I added early in the development of AccessKit, that was active even in release builds.
> fix(consumer): Drop printing of detached nodes before panic

- consumer/src/lib.rs
- consumer/src/node.rs
- consumer/src/tree.rs
- platforms/windows/src/node.rs
This way, when we switch from a big `Node` struct with many fields, to something with getter methods, the platform adapters won't be affected. This was already almost true; I just had to expose the `selected` field.
This PR also drops unnecessary exports of `accesskit::Node` and `accesskit::Tree` as `NodeData` and `TreeData`. Users of the consumer crate should not be concerned with these structs.
> refactor(consumer)!: Make `Node::data` private to the crate

- common/Cargo.toml
- common/src/lib.rs
- consumer/src/lib.rs
- consumer/src/node.rs
- consumer/src/tree.rs
- platforms/windows/examples/hello_world.rs
- platforms/windows/src/tests/simple.rs
- platforms/windows/src/tests/subclassed.rs
- platforms/winit/examples/simple.rs
This is another change that's inconvenient for test code, but it eliminates a lot of compiled code for copying around the huge `Node` struct.
> refactor!: Wrap `TreeUpdate` nodes in `Arc`

- common/src/lib.rs
- consumer/src/tree.rs
I'm making this change for two reasons:
* Comparing instances of the current, huge `Node` struct is expensive. Eliminating this comparison reduces the size of the Windows example by several kilobytes, whether optimizing for speed or size.
* When I implement the transition to a `Node` trait, comparing across implementations of that trait would be even more expensive, since it would require dynamically dispatched method calls for every property.
This change does eliminate an optimization for immediate-mode GUIs. But honestly, sending a whole tree for every frame isn't good enough for performance anyway; if nothing else, it wastes memory allocations. So I think toolkits will just have to do their own optimizations to avoid sending full trees unnecessarily.
> fix(consumer): Don't compare node contents during tree update

- consumer/src/lib.rs
- consumer/src/node.rs
- consumer/src/tree.rs
- platforms/windows/src/adapter.rs
- platforms/windows/src/node.rs
This PR has the following high-level design changes:
* Removed `WeakNode` from `accesskit_consumer`. I found that this approach forced AccessKit to do the full node lookup process whether or not it was necessary for a particular platform adapter method. Also, for some future uses of `accesskit_consumer`, such as an in-process self-voicing module, something like `WeakNode` won't be needed at all.
* In `accesskit_consumer`, the methods to perform actions are now on `Tree` rather than `Node`. This change combined with the previous one means that `Node` no longer needs a reference (whether direct or indirect) back to `Tree`.
* As a result of these changes, we can drop the `TreeReader` struct. `Node` only needs a reference to `tree::State`, which is now exported as `TreeState`, and …
> refactor(consumer)!: Optimize tree access and change handling

- common/src/lib.rs
I accidentally increased the MSRV to 1.62 when I used the new feature of deriving `Default` on an enum. That would block integration with egui, so I have to manually implement `Default` instead.
> fix(common): Restore compatibility with Rust 1.61

- platforms/winit/src/lib.rs
I need this for my egui integration, because egui's official winit integration expects the user event type to derive `Debug`. And of course, this is good to have anyway.
> fix(platforms/winit): Derive `Debug` on `ActionRequestEvent`

- common/src/lib.rs
- consumer/src/iterators.rs
- consumer/src/lib.rs
- consumer/src/node.rs
- platforms/windows/src/adapter.rs
- platforms/windows/src/node.rs
I think the `ignored` field doesn't belong in the schema. Toolkit and application developers shouldn't be required to indicate which nodes should be excluded from the platform tree. This highlights a difference in design requirements between AccessKit and the Chromium accessibility schema; the latter is only intended for internal use within Chromium, not to be approachable to arbitrary toolkit or application developers.
Also, the criteria for determining which nodes should be excluded from the platform tree may be platform-dependent. And there may be cases where we want to traverse only the nodes that meet very specific criteria. So I believe we need to modify `following_unignored_siblings` and related functions to take a caller-supplied filter function.
It was convenient to mark …
> refactor!: Drop the `ignored` field and implement generic filtered tree traversal

- common/src/lib.rs
- consumer/src/lib.rs
- consumer/src/node.rs
- consumer/src/text.rs
- consumer/src/tree.rs
- platforms/windows/src/adapter.rs
- platforms/windows/src/node.rs
- platforms/windows/src/text.rs
- platforms/windows/src/util.rs
This allows screen readers and other ATs to provide the expected feedback when editing text on Windows.
The easiest way to try it out with a working application is to try one of the examples in the corresponding [egui branch](https://github.com/mwcampbell/egui/tree/accesskit-text).
The primary missing feature is support for rich text, including text formatting information.
This ought to have tests, but I figured I'd get the implementation into code review.
> feat!: Text range support

- Cargo.lock
- platforms/windows/Cargo.toml
- platforms/windows/examples/hello_world.rs
- platforms/windows/src/node.rs
- platforms/windows/src/tests/mod.rs
- platforms/windows/src/tests/simple.rs
- platforms/windows/src/text.rs
- platforms/windows/src/util.rs
- platforms/winit/Cargo.toml
I'm not updating to 0.43.0 at this time because my actual goal in making this change now is to satisfy egui's CI, particularly the requirement that the egui workspace not have multiple versions of the same crate, and to do that, we need to use windows-rs 0.42.0.
> fix(platforms/windows)!: Update to windows-rs 0.42.0

- platforms/winit/src/lib.rs
When integrating AccessKit with some winit-based projects, such as the Bevy game engine, it's more convenient to define a custom implementation of the `ActionHandler` trait than to plumb a winit `EventHandlerProxy` that supports a custom user event type. It's easy to refactor the winit adapter to allow this.
> feat(platforms/winit): Allow a custom action handler

- Cargo.lock
- consumer/Cargo.toml
- consumer/src/lib.rs
- consumer/src/node.rs
- consumer/src/tree.rs
- platforms/windows/src/adapter.rs
- platforms/windows/src/node.rs
The `im` crate is under the MPL, which isn't permissive enough for some users. To eliminate the dependency on this crate, we can no longer have a complete snapshot of the old version of the tree when processing tree changes. So we need to introduce the concept of a detached node, and create detached nodes for the old versions of nodes that have been changed or removed.
In the Windows adapter, this change also clarifies the purpose of `NodeWrapper`; that type (now an enum) is now only used when we might need to get a property of a detached node.
> refactor(consumer)!: Eliminate the dependency on `im` due to licensing

- platforms/winit/Cargo.toml
winit's wayland-csd-adwaita feature, which is enabled by default, introduces some dependencies which are rejected by the Bevy game engine's CI. So the accesskit_winit crate now disables this feature. But users of accesskit_winit can still enable this feature if they want.
> fix(platforms/winit): Eliminate some problematic indirect dependencies

- Cargo.lock
- platforms/windows/src/lib.rs
- platforms/winit/Cargo.toml
- platforms/winit/src/platform_impl/windows.rs
This simplifies dependency maintenance in downstream crates, including our own `accesskit_winit`.
> fix(platforms/windows): Re-export the windows-rs HWND type

- platforms/windows/src/lib.rs
I forgot that for a clean integration that doesn't require window subclassing, the caller needs more types from windows-rs.
> fix(platforms/windows): Re-export more types from windows-rs

- platforms/windows/src/node.rs
Narrator doesn't read a spinner if the minimum and maximum values are set to negative and positive infinity. So, following the example set by Edge, the default minimum and maximum are now both 0. Of course, it's better for a toolkit to expose the minimum and maximum if they're set.
> fix(platforms/windows): Change default minimum and maximum for range value pattern

- consumer/src/text.rs
On Windows, spin buttons are usually editable, and JAWS assumes that they are. So this PR adds spin buttons to the set of roles that can support text ranges.
> fix(consumer): Allow editable spin buttons

- consumer/src/text.rs
- platforms/windows/src/node.rs
The egui `DragValue` widget will be like this.
BTW, I'm no longer including the parenthesized part in the prefix at the beginning of commit messages, because it doesn't have the purpose that I thought it did in release-please; it just clutters the change logs.
> fix: Gracefully handle nodes that only support text ranges some of the time

- platforms/winit/Cargo.toml
- release-please-config.json
The main reason for this PR is to try to re-bootstrap release-please. I just have to change _something_ in platforms/winit to see if this will fix the problem with automatically creating releases of this crate.
> fix: Reduce the winit version requirement to match egui

- platforms/macos/src/lib.rs
For the same reason as we now re-export windows-rs types in the Windows adapter.
> fix: Re-export types from objc2

- platforms/macos/src/adapter.rs
- platforms/macos/src/appkit/view.rs
- platforms/macos/src/node.rs
I didn't realize that on macOS, a view's coordinates can be flipped so that y is top-down (as it is on other platforms). druid-shell and its successor glazier do this, so we need to handle it.
> fix: Handle views with flipped coordinates

- platforms/macos/src/adapter.rs
- platforms/macos/src/node.rs
By default, VoiceOver determines its navigation order based on the positions of the nodes. This is bad for complex layouts.
To make this work, the root node must not be filtered out of the platform tree. Luckily, VoiceOver doesn't present a top-level group as a separate thing that the user has to interact with. We still have to be careful not to expose that node as focused when the focus is on the window itself, though.
> fix: Make VoiceOver move through nodes in logical order

- .github/workflows/release-please.yml
Hoping this will fix the ongoing failure to create change log entries and releases for the winit adapter. It looks like it will, based on my dry run of the latest release-please from the CLI on my own machine.
> chore: Update the release-please GitHub action

- platforms/macos/src/adapter.rs
- platforms/macos/src/appkit/view.rs
- platforms/macos/src/node.rs
I incorrectly assumed that the relevant accessibility methods used physical (DPI-dependent) coordinates. A Retina Mac user noticed that the VoiceOver highlight was wrong. I already asked him to test this fix.
> fix: Correctly apply the DPI scale factor to coordinates

- platforms/macos/src/node.rs
I think this is a good thing to add before implementing the `NSAccessibility` text methods, which an AT shouldn't try to call on nodes that don't support text ranges. Since I've chosen to have a single Objective-C class for all types of AccessKit nodes, it's useful to let ATs know which methods are and are not supported for a particular node.
I know this method is being used, because before I added `accessibilityRoleDescription` to the list of selectors that are allowed by default, VoiceOver didn't speak some role descriptions, like "slider", "stepper", and "button". Maybe we'll eventually discover more selectors that need to be on the default allow list.
> fix: Expose which accessibility selectors are actually allowed for a particular node

- .github/workflows/ci.yml
- consumer/src/node.rs
- platforms/windows/examples/hello_world.rs
- platforms/windows/src/tests/mod.rs
- platforms/windows/src/util.rs
Rust 1.66 introduced a couple of new lints. There's also one from the Windows example that wasn't caught by the CI.
> chore: Fix clippy lints and make CI more comprehensive

- consumer/src/node.rs
- consumer/src/text.rs
- platforms/macos/src/adapter.rs
- platforms/macos/src/appkit/accessibility_constants.rs
- platforms/macos/src/event.rs
- platforms/macos/src/lib.rs
- platforms/macos/src/node.rs
- platforms/macos/src/util.rs
This should be on par with the Windows adapter, meaning support for single-line and multi-line edit controls, but without exposing text formatting attributes or other rich text features. To test with a real toolkit implementation, use [this egui branch](https://github.com/mwcampbell/egui/tree/accesskit-macos-basic-text). egui itself required only one minor fix, which is already merged; the existing integration in egui that was tested with the Windows adapter was mostly fine already.
> feat: Text support on macOS

- platforms/macos/src/node.rs
If we expose the window title on the group element that we expose for the root of the window, VoiceOver behavior is broken. On macOS, VoiceOver gets the window title from the Cocoa `NSWindow`.
> fix: Don't expose the window title in our root element on macOS

- consumer/src/text.rs
- platforms/macos/src/util.rs
- platforms/windows/src/text.rs
I discovered that NVDA was unable to move forward to the next line of text when the current line was wrapped (i.e. ended with a soft line break). This revealed some flaws in my current approach to setting the bias (also called affinity) for text positions on the edge of a soft line break. The new approach is more explicit. This fix also ensures that the start of a non-degenerate range is never on the end of a previous line. I added test coverage for all of this, in the tests for the consumer crate. I should still write tests for the Windows adapter sometime in the future.
> fix: More reliable handling of the edge case for wrapped lines

- platforms/windows/src/text.rs
This prevented Narrator on Windows 11 from reading characters, selection changes, and possibly other things. It might have also affected other assistive technologies that use the same newer UI Automation API that was introduced in Windows 11 and is now being used by Narrator.
fixes #189
> fix: Correct broken UIA method implementation that was incompatible with Windows 11 ATs

- platforms/windows/examples/hello_world.rs
- platforms/windows/src/node.rs
- platforms/windows/src/tests/simple.rs
- platforms/windows/src/util.rs
UIA itself normally does this automatically. But for an AT that uses the UIA Remote Operations API introduced in Windows 11, such as the Windows 11 version of Narrator, this fallback isn't available for providers that don't use COM threading, such as ours. As a result, Windows 11 Narrator was unable to find the window context for the current focus if something other than the window is immediately focused. We don't want to switch to COM threading, since the ability to run UIA methods independently of the UI thread is a key benefit of the AccessKit architecture. We also don't want to require integrators to provide the window title as the name of the root node if we can avoid it. So, this PR implements our own fallback. It also modifies the Windows example and test code to clarify that the …
> fix: Provide fallback property implementations for the window root

- platforms/macos/src/appkit/accessibility_constants.rs
- platforms/macos/src/appkit/accessibility_functions.rs
- platforms/macos/src/appkit/mod.rs
- platforms/macos/src/event.rs
- platforms/macos/src/node.rs
Cocoa accessibility doesn't seem to have live regions as such, so we post announcement notifications instead. This is also what Chromium and Firefox do.
> feat: Live regions on macOS

- platforms/macos/Cargo.toml
fixes #199
I'll merge this as soon as it passes CI, as it is the simplest, safest possible fix for the broken build reported in that issue.
> fix: Pin objc2 dependency to 0.3.0-beta.3

- platforms/winit/Cargo.toml
Bevy prefers to keep these features enabled by default and let the user choose which of them to enable. Since the Unix backend in `accesskit_winit` didn't actually need to use anything specific to X11 or Wayland, we can disable these features too.
> fix: Don't force winit's X11 and Wayland features to be enabled

- platforms/winit/Cargo.toml
- platforms/winit/examples/simple.rs
- platforms/winit/src/lib.rs
- platforms/winit/src/platform_impl/mod.rs
The current effort to integrate AccessKit in the Bevy game engine is meeting with some resistance because of the number of new dependencies added by the AccessKit Unix adapter. So, as a compromise, this PR allows just the Unix adapter to be turned off with a feature in accesskit_winit. If the feature is disabled, then accesskit_winit will use the null adapter on Unix platforms, as it does for unsupported platforms.
> feat: Feature-gate the Unix adapter in accesskit_winit

- Cargo.lock
- platforms/windows/Cargo.toml
- platforms/windows/examples/hello_world.rs
- platforms/windows/src/adapter.rs
- platforms/windows/src/subclass.rs
- platforms/windows/src/tests/simple.rs
- platforms/windows/src/text.rs
- platforms/windows/src/util.rs
The immediate motivation is a CI failure in the Bevy AccessKit PR. While Bevy is indirectly depending on windows-rs 0.43, I was told we should go ahead and update to 0.44.
> fix: Update windows-rs to 0.44

- platforms/macos/src/adapter.rs
- platforms/macos/src/appkit/view.rs
- platforms/macos/src/node.rs
AccessKit allows the root node to omit the bounding rectangle. On Windows and Linux, we can use the window's own rectangle as a fallback. This PR implements the equivalent behavior on macOS.
> fix: Fix problems related to the root node

- consumer/Cargo.toml
- platforms/macos/Cargo.toml
- platforms/unix/Cargo.toml
- platforms/windows/Cargo.toml
- platforms/winit/Cargo.toml
Fixes #233
Unfortunately, the only way I know to do this with release-please is to make dummy changes to the contents of these crates. A blank line added to the end of Cargo.toml is the most innocuous possible change that will do the job.
> fix!: Force a non-patch version bump in downstream crates

- .github/workflows/bindings.yml
- bindings/c/examples/windows/build.bat
Addresses https://github.com/accesskit/accesskit/pull/230#issuecomment-1490852698, initially raised by @bruvzg
Test package: [accesskit_c-v0.2.0](https://github.com/DataTriny/accesskit/releases/download/accesskit_c-v0.2.0/accesskit_c-v0.2.0.zip)
I've used these workflow runs as an opportunity to try and fix the install name of the dynamic library on macOS. Looking at the logs I see a result, but does it actually work? If anyone with access to a Mac could confirm, that would be wonderful!
> fix: Improve C bindings package directory structure

- bindings/c/cbindgen.toml
- bindings/c/src/macos.rs
Fixes #242 
It compiles, does it actually do what it is supposed to?
Feedback appreciated.
CC @bruvzg
> fix: Remove objc and Core Foundation types from C bindings public API

- Cargo.lock
- platforms/unix/Cargo.toml
- platforms/unix/src/adapter.rs
- platforms/unix/src/atspi/bus.rs
- platforms/unix/src/util.rs
- platforms/winit/Cargo.toml
Fixes #227 
This PR adds new crate features to accesskit_unix and accesskit_winit. They are designed to specify which async runtime to use for D-Bus communication:
- `async-io`: rely on zbus's support for async-std,
- `tokio`: use a dedicated tokio runtime.
The default is `async-io`, which keeps the current behavior unchanged.
This is indeed suboptimal if zbus is used somewhere else as we won't use a common runtime in the case of tokio.
> feat: Add features for async runtimes on Linux

- Cargo.toml
I've wanted to add these for a while, and we'll soon release a new version of our C bindings, so now is a good time.
The `debug` flag enables as much debug info as possible in release builds without compromising optimizations. This is important for doing postmortem debugging of problems found in release builds. Windows uses a setting like this in its release builds, and I believe Chromium does too.
Maximizing optimization for size is perhaps more controversial, but I believe it's the best choice for us. Our library will look better to some decision-makers if it's smaller, and the difference is particularly dramatic with the Unix adapter. If we ever find that this decision noticeably hurts real-world performance, I'll be happy to reverse it.
> chore: Add compiler settings to our release profile

- platforms/macos/Cargo.toml
MacOS adapter [documentation](https://docs.rs/crate/accesskit_macos/latest) is broken, and might have been for a long time actually. This is because docs.rs uses a Linux target to build the documentation by default, hence objc2 fails to compile.
Looking at other objc2 dependent crates I think this change should solve the issue, but I can't guarantee.
> fix: Set proper target to build accesskit_macos documentation

- bindings/c/src/macos.rs
- platforms/macos/src/appkit/window.rs
- platforms/macos/src/subclass.rs
This easily solves the issue we're having with #250, where we'd otherwise have to either write a little Objective-C or do some low-level stuff with the ObjC runtime from C code to make the SDL example compile on macOS. It might also help some Rust users, which is why I implemented the alternate constructor in the platform adapter itself.
> feat: Add window-based constructor to macOS subclassing adapter

- Cargo.lock
The nightly builds removed something that nighly builds of `proc-macro2` had used and so the version of `proc-macro2` that we use no longer works.
The easiest thing to do is to update that dependency.
More details upstream at https://github.com/rust-lang/rust/issues/113152
This can be confirmed to work and fix the issue by running `cargo +nightly build` with and without this change using a recent enough nightly build. Without this change, it fails.
> deps: Update proc-macro2 to fix nightly build.

- Cargo.toml
This fixes warnings like this:
```
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
```
> Use resolver 2 in virtual workspace.

- bindings/c/cbindgen.toml
- bindings/c/examples/windows/hello_world.c
- bindings/c/src/common.rs
- bindings/c/src/macos.rs
- bindings/c/src/unix.rs
- bindings/c/src/windows.rs
`accesskit_tree_update` is now an opaque struct like the other wrapper structs around boxed types. I think this API is safer, lower-overhead, and more pleasant to use (as C APIs go). It will also let us experiment with passing a serialized tree update across the FFI boundary, as we did in the proof-of-concept Unity plugin, by adding a function like `accesskit_tree_update_from_json`.
> refactor!: New C API for tree updates

- common/src/lib.rs
I think I need this for my JNI bindings.
> feat: Support the enumn crate in all public enums

- bindings/c/src/macos.rs
- platforms/macos/src/lib.rs
- platforms/macos/src/patch.rs
This fixes the macOS focus problem discussed in #250.
@madsmtm I had to copy some code from objc2 in order to add a method to an existing class. That was the only solution I could find; creating a subclass and changing the class of the window instance led to very broken behavior (the window never appeared), likely because `NSWindow` uses KVO.
> feat: Workaround for libraries that put the macOS keyboard focus on the window rather than the content view

- .github/workflows/ci.yml
- Cargo.lock
- platforms/windows/CHANGELOG.md
- platforms/windows/Cargo.toml
- platforms/windows/src/node.rs
- platforms/windows/src/tests/mod.rs
- platforms/windows/src/text.rs
- platforms/windows/src/util.rs
Looking to reduce binary size and compile times on Windows by only having one version of the windows crate in my apps.
Should the cargo.lock file be removed from this repo? I was under the impression it normally [should be ignored for libraries](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html) and it is the bulk of the lines changed in this PR.
> Update windows crate to v0.48

- Cargo.lock
- common/Cargo.toml
- common/src/lib.rs
Changes to the `common` crate extracted from #269 as to avoid messing up semver of the other crates.
> fix: Support the pyo3 crate in all public enums

- consumer/src/node.rs
- consumer/src/text.rs
- consumer/src/tree.rs
- platforms/macos/src/event.rs
- platforms/macos/src/node.rs
- platforms/windows/src/adapter.rs
- platforms/windows/src/node.rs
When a provider properly implements text field controls, setting the value property on the outer text field node is redundant, because the text is already provided in the inner inline text boxes. I expect that this would be a performance problem for large amounts of text. So now, `accesskit_consumer` provides its own value property for single-line text controls, based on the inner text. For multi-line controls without an outer value property, the macOS adapter fires value change events as appropriate, just as the Windows adapter already fires text change events. I've tested these changes on both Windows and macOS using a modified version of egui that doesn't set the value property on the text field.
> fix: Support text fields without a value property

- Cargo.lock
- bindings/c/examples/sdl/hello_world.c
- bindings/c/examples/windows/hello_world.c
- bindings/c/src/common.rs
- common/src/lib.rs
- consumer/src/lib.rs
- consumer/src/node.rs
- consumer/src/text.rs
- consumer/src/tree.rs
- platforms/macos/Cargo.toml
- platforms/unix/Cargo.toml
- platforms/windows/Cargo.toml
- platforms/windows/examples/hello_world.rs
- platforms/windows/src/node.rs
- platforms/windows/src/tests/simple.rs
- platforms/windows/src/tests/subclassed.rs
- platforms/windows/src/util.rs
- platforms/winit/examples/simple.rs
> refactor!: Switch to simple unsigned 64-bit integer for node IDs

- bindings/c/examples/sdl/hello_world.c
- bindings/c/examples/windows/hello_world.c
- bindings/c/src/common.rs
- bindings/c/src/macos.rs
- bindings/c/src/unix.rs
- bindings/c/src/windows.rs
- common/src/lib.rs
- consumer/src/lib.rs
- consumer/src/node.rs
- consumer/src/text.rs
- consumer/src/tree.rs
- platforms/macos/src/adapter.rs
- platforms/macos/src/subclass.rs
- platforms/unix/src/adapter.rs
- platforms/windows/examples/hello_world.rs
- platforms/windows/src/adapter.rs
- platforms/windows/src/subclass.rs
- platforms/windows/src/tests/mod.rs
- platforms/windows/src/tests/simple.rs
- platforms/windows/src/tests/subclassed.rs
- platforms/winit/examples/simple.rs
- platforms/winit/src/lib.rs
- platforms/winit/src/platform_impl/macos.rs
- platforms/winit/src/platform_impl/null.rs
- platforms/winit/src/platform_impl/unix.rs
- platforms/winit/src/platform_impl/windows.rs
I'm making this change for two reasons. First, I've found that toolkit developers are confused by the existing rules around `TreeUpdate::focus`, and they tend to get it wrong. Second, the old design doesn't fully align with [my proposed vision for a new accessibility architecture for GNOME and other free desktops](https://github.com/mwcampbell/ng-a11y), because it mixes some global state into the tree update.
I've prioritized doing this change now because I already did the `NodeId` breaking change, so I think we should do all anticipated breaking changes at once.
> refactor!: Decouple in-tree focus from host window/view focus

- bindings/c/src/common.rs
- common/src/lib.rs
- consumer/src/tree.rs
I believe this was always overly specific to the requirements of Chromium on Android. I'm sure the current rules around relative coordinates, especially when using transforms, are flexible enough to allow for such special cases.
> fix!: Drop `Tree::root_scroller`

- common/src/lib.rs
- consumer/src/text.rs
- platforms/macos/src/node.rs
- platforms/unix/src/node.rs
- platforms/windows/src/node.rs
This just adds the role and maps it appropriately in the platform adapters. To really make this useful, we may need to fire some extra events, and we still need to implement text support in the Unix adapter. I'm not sure if we can really do anything useful with this on Windows without implementing a way of pushing AccessKit tree updates directly to ATs like NVDA, as I've had in mind for a while. But I want to start putting the necessary pieces in place.
> feat: Add role for terminals

- platforms/winit/Cargo.toml
Should fix doc build for https://docs.rs/crate/accesskit_winit/
> Fix doc build for accesskit_winit

- bindings/c/Cargo.toml
Partial fix for `cargo doc --all --no-deps`.
But on Linux you also need `--features winit/wayland` and then still get an error due to `platforms/macos`.
> bindings/c: disable doc

- consumer/src/filters.rs
- consumer/src/iterators.rs
- consumer/src/lib.rs
- consumer/src/node.rs
- platforms/macos/src/adapter.rs
- platforms/macos/src/event.rs
- platforms/macos/src/filters.rs
- platforms/macos/src/lib.rs
- platforms/macos/src/node.rs
- platforms/unix/src/adapter.rs
- platforms/unix/src/filters.rs
- platforms/unix/src/lib.rs
- platforms/unix/src/node.rs
- platforms/windows/src/adapter.rs
- platforms/windows/src/filters.rs
- platforms/windows/src/lib.rs
- platforms/windows/src/node.rs
The Windows and Unix adapters use duplicated filter functions, and I decided that the macOS adapter should use those same filters as well. So now those functions are defined in the consumer crate.
> fix: Use common filters across platform adapters

- bindings/c/src/common.rs
- common/src/lib.rs
I decided that, as shown in #284, these properties only add unnecessary complexity for GUI toolkit developers. None of the platform adapters use them, and there's probably no way they ever could. The equivalent properties in Chromium are only used by ChromeVox. My understanding is that the only purpose of these properties is to allow tabbing to the correct control when a screen reader's browse mode, scan mode, or equivalent is active, and the screen reader's cursor is not on a focusable control. In my opinion, that purpose is better served by the existing `SetSequentialFocusNavigationStartingPoint` action, which will remain optional for toolkit developers.
> fix!: Drop next/previous focus properties

- platforms/windows/src/text.rs
When calling `Vec::new()` and then immediately calling `Vec::reserve()` on the resulting vector, it is more concise and less complex to just use `Vec::with_capacity()` instead.
This is a new clippy lint coming in 1.73.
> clippy: Fix reserve_after_initialization warning.

- bindings/c/src/common.rs
- common/src/lib.rs
- platforms/macos/src/context.rs
- platforms/macos/src/node.rs
- platforms/unix/src/adapter.rs
- platforms/unix/src/context.rs
- platforms/unix/src/node.rs
- platforms/windows/examples/hello_world.rs
- platforms/windows/src/adapter.rs
- platforms/windows/src/context.rs
- platforms/windows/src/node.rs
- platforms/windows/src/subclass.rs
- platforms/windows/src/tests/simple.rs
- platforms/windows/src/tests/subclassed.rs
- platforms/windows/src/text.rs
- platforms/winit/src/lib.rs
- platforms/winit/src/platform_impl/unix.rs
- platforms/winit/src/platform_impl/windows.rs
I believe this isn't controversial like my previous, abandoned PR or the other API change I'm currently considering. I'm pretty sure it's conceptually correct, because an action handler needs to mutate the application's state, and it's better to have the platform adapters handle interior mutability in the way that's appropriate for each platform's threading requirements than to make the user do it. This simplifies the winit adapter and makes the C API a bit safer.
> refactor!: Make `ActionHandler::do_action` take `&mut self`

- Cargo.lock
- platforms/unix/Cargo.toml
- platforms/unix/src/atspi/bus.rs
- platforms/unix/src/atspi/interfaces/accessible.rs
- platforms/unix/src/atspi/interfaces/action.rs
- platforms/unix/src/atspi/interfaces/application.rs
- platforms/unix/src/atspi/interfaces/component.rs
- platforms/unix/src/atspi/interfaces/events.rs
- platforms/unix/src/atspi/interfaces/value.rs
- platforms/unix/src/atspi/object_address.rs
- platforms/unix/src/node.rs
- By updating to atspi 0.19 we get the new [Live](https://docs.rs/atspi/latest/atspi/enum.Live.html) enum which will be needed to implement live regions on Unix.
- By updating zbus we get some small API improvements, notably around property methods, allowing us to remove quite a few `unwrap` calls.
> chore: Update Unix adapter dependencies

- AUTHORS
- bindings/c/examples/sdl/hello_world.c
- bindings/c/examples/windows/hello_world.c
- bindings/c/src/common.rs
- bindings/c/src/unix.rs
- common/src/lib.rs
- consumer/src/tree.rs
- platforms/unix/src/adapter.rs
- platforms/unix/src/atspi/interfaces/application.rs
- platforms/windows/examples/hello_world.rs
- platforms/windows/src/node.rs
- platforms/windows/src/util.rs
- platforms/winit/examples/simple.rs
- platforms/winit/src/platform_impl/unix.rs
Similar to the unix crate, this adds `app_name`, `toolkit_name` and `toolkit_version` parameters to the adapter constructors.
- FrameworkIdProperty: exposes `toolkit_name`
- ProviderDescriptionProperty: exposes `app_name (toolkit_name toolkit_version)`
fixes #280
> feat!: Allow providing app_name, toolkit_name and toolkit_version in Tree, remove parameters from unix adapter constructor

- platforms/windows/examples/hello_world.rs
- platforms/windows/src/tests/mod.rs
I don't feel confident in how I fixed this warning, from a lint introduced in 1.72:
```
warning: usage of an `Arc` that is not `Send` or `Sync`
--> platforms\windows\src\tests\mod.rs:273:9
|
273 | /         Arc::new(Self {
274 | |             mutex: Mutex::new(None),
275 | |             cv: Condvar::new(),
276 | |         })
| |__________^
|
= note: the trait `Send` is not implemented for `ReceivedFocusEvent`
= note: the trait `Sync` is not implemented for `ReceivedFocusEvent`
= note: required for `Arc<ReceivedFocusEvent>` to implement `Send` and `Sync`
= help: consider using an `Rc` instead or wrapping the inner type with a `Mutex`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#arc_with_non_send_sync
= note: …
```
> chore: Fix some clippy warnings

- .clippy.toml
- bindings/c/src/lib.rs
- consumer/src/iterators.rs
This also includes a `.clippy.toml` to disable warnings about some identifiers that don't need backticks when running `clippy::doc_markdown`.
> docs: Markdown fixes.

- platforms/windows/src/tests/mod.rs
I realized that the recent switch from `Arc` to `Rc` in this event handler was incorrect, because the event handler is in fact called from a different thread from the one on which it was created. To address the original clippy warning in the safest way possible, I created a new wrapper struct, `SendableUiaElement`, that implements `Send`. The compiler can automatically implement `Send` and `Sync` on `ReceivedFocusEvent` from there. I also added a static assertion that `Send` and `Sync` are implemented on `FocusEventHandler`.
> fix: Make the test focus event handler thread-safe again

- Cargo.lock
- platforms/winit/Cargo.toml
- platforms/winit/examples/simple.rs
- platforms/winit/src/platform_impl/macos.rs
- platforms/winit/src/platform_impl/windows.rs
I'm working on updating bevy to next winit version: https://github.com/bevyengine/bevy/pull/8745 ; a simple winit bump seems enough, but I noticed examples failing so I updated them. I'm sharing in case it's useful.
> deps!: Bump winit to 0.29

- platforms/windows/src/tests/mod.rs
- platforms/windows/src/tests/subclassed.rs
I see from a [recent failed CI job](https://github.com/AccessKit/accesskit/actions/runs/6755825086/job/18364643052) that the subclassing test can also intermittently fail. I noticed that my own test broke the cardinal rule of using the subclassing adapter: the window must be created invisible. So I fixed that, but I also made a couple of changes:
* The test no longer repeatedly calls `UiaHasServerSideProvider`, and it doesn't drop and re-create the adapter, because these things aren't testing realistic scenarios. In real use, the window is created invisible, the adapter is created once afterward, and nobody would call `UiaHasServerSideProvider` (or equivalent) on the window until after the adapter is created. I've seen that sometimes `UiaHasServerSIdeProvider` appears to cache the result …
> fix: Make the Windows subclassing test more robust

- Cargo.lock
- platforms/windows/Cargo.toml
- platforms/windows/src/tests/subclassed.rs
Extracted from #256 
Update winit (and therefore raw-window-handle) to their latest version for accesskit_windows test suite.
> deps: Bump accesskit_windows dev dependency to winit 0.29

- platforms/winit/examples/simple.rs
- platforms/winit/src/lib.rs
- platforms/winit/src/platform_impl/macos.rs
- platforms/winit/src/platform_impl/null.rs
- platforms/winit/src/platform_impl/unix.rs
- platforms/winit/src/platform_impl/windows.rs
Closes #300 
The name `on_event` suggests that this function won't have side effects, which is not the case.
We received strong push-back from developers who don't want AccessKit to filter events. We previously agreed on keeping the mechanism around even though we didn't use it for keyboard events on Unix. Even though we might need it in the future for other features, this is not currently the case, therefore it is hard to convince people to use it. I propose to remove it for now.
> fix!: Rename `accesskit_winit::Adapter::on_event` to `process_event`

- Cargo.lock
- platforms/winit/Cargo.toml
- platforms/winit/src/platform_impl/macos.rs
- platforms/winit/src/platform_impl/windows.rs
Following up on an [earlier comment](https://github.com/AccessKit/accesskit/pull/305#issuecomment-1793515487), I don't think it would be right for us to do a new release that depends on an old version of raw-window-handle, if we can easily avoid it. So this PR switches accesskit_winit to use rwh_06. @Vrixyz I believe this can coexist with your code that requires rwh_05, since it seems that those winit features don't actually conflict, but please check.
> fix: Use raw-window-handle 0.6

- platforms/winit/src/platform_impl/unix.rs
> fix: Account for window decorations when `accesskit_winit::Adapter::process_event` receives a resizing event on Unix

- CONTRIBUTING.md
- Cargo.lock
- platforms/unix/Cargo.toml
- platforms/unix/src/adapter.rs
Relates to #317 
Using the `pin!` macro bumps our MSRV to 1.68. I've checked downstream crates and I think this is acceptable, but I can find a way around if not.
> chore: Bump async-channel dependency

- Cargo.lock
- platforms/winit/Cargo.toml
- platforms/winit/src/lib.rs
- platforms/winit/src/platform_impl/macos.rs
- platforms/winit/src/platform_impl/windows.rs
This allows using accesskit with current and older versions of wgpu. Typically this is a requirement for game developers, or low level UI toolkit developers.
Added the `rwh_05` and `rwh_06` feature flags to the `accesskit_winit` crate.
This allows consumers of the `accesskit_winit` crate to pick and chose which version of `raw-window-handle` `accesskit_winit` will depend on.
* `rwh_05` enables the `winit` `rwh_05` feature flag, which uses the `raw-window-handle` version `0.5`.
* `rwh_06` is similar to `rwh_05`, but for `raw-window-handle` version `0.6`.
See https://github.com/rust-windowing/winit/pull/3075 for a discussion of why this is wanted.
`rwh_06` is enabled by default, following `winit`'s convention. If both features are enabled at the same time, a `compile_error!` is emitted. …
> Add a rwh_05 feature flag

- platforms/unix/Cargo.toml
This is really just a dummy commit because the previous one, having been tagged with `chore`, won't get release-please to release a new version of the unix adapter.
> fix: Bump async-channel dependency to `2.1.1`

- platforms/winit/Cargo.toml
I have to do a dummy commit for the winit change as well, because adding a new default feature that is required for the crate to function is a breaking change.
> fix!: Force a semver-breaking release for the winit rwh feature additions

- platforms/winit/src/lib.rs
- platforms/winit/src/platform_impl/macos.rs
- platforms/winit/src/platform_impl/null.rs
- platforms/winit/src/platform_impl/unix.rs
- platforms/winit/src/platform_impl/windows.rs
As discussed in #324, the `update` method on the winit `Adapter` isn't really used anymore. Since upcoming changes to the Unix adapter will render this method useless on this platform, this PR removes it.
`update_if_active` is now the only way to push tree updates.
Note that I haven't removed `update` methods from the various subclassing adapters, but they might be useless as well now.
> fix!: Remove `accesskit_winit::Adapter::update`

- bindings/c/examples/sdl/hello_world.c
> refactor: Remove unused `accesskit_sdl_adapter_update` function from the SDL example

- Cargo.toml
- bindings/c/.cargo/config.toml
I've decided that the `debug` and `panic` settings in the Cargo release profile need to be decided on a per-binding basis. I think we're in agreement that these settings should remain as they are for the C binding. But for the Python binding, I think we want `debug = false` and `panic = "unwind"`. Whether by accident or design, it seems to be standard practice to not ship full debug info with Python wheels, but to leave the shared libraries unstripped on non-Windows platforms. The default setting of `debug = false` accomplishes this. As for the `panic` setting, PyO3 can convert a Rust panic into a Python exception as long as we leave the `panic` setting at its default. That does increase binary size somewhat, but I think it's more important for the Python binding to behave as Python users …
> chore: Move `debug` and `panic` settings to C binding

- Cargo.lock
- bindings/c/examples/sdl/hello_world.c
- bindings/c/src/common.rs
- bindings/c/src/macos.rs
- bindings/c/src/unix.rs
- bindings/c/src/windows.rs
- platforms/unix/Cargo.toml
- platforms/unix/src/adapter.rs
- platforms/unix/src/atspi/bus.rs
- platforms/unix/src/atspi/mod.rs
- platforms/unix/src/context.rs
- platforms/unix/src/node.rs
- platforms/unix/src/util.rs
- platforms/winit/src/platform_impl/unix.rs
Fixes #314 
When a Unix adapter is created, we now start monitoring the D-Bus session bus for property change signals, which indicate if assistive technologies are currently running. If this becomes true, all currently registered adapters will be initialized. If for some reason the AT-SPI bus disappear, tree updates will still happen but nothing will be sent through D-Bus. If the AT-SPI bus is launched again, the connection will be re-established, the D-Bus object server will be populated and signals will be emitted like before.
> fix!: Lazily activate Unix adapters

- common/src/lib.rs
> fix: Document the `role_description` node property

- consumer/src/node.rs
- platforms/macos/src/node.rs
- platforms/unix/src/atspi/interfaces/accessible.rs
- platforms/unix/src/node.rs
- platforms/windows/src/node.rs
Revamping an old branch, initial work by @mwcampbell.
Implement support for the `role_description` property on all adapters:
- Documented the fact that this property should be used sparingly,
- Tweaked the macOS and Windows implementations after rebase,
- On Unix: implemented the `GetLocalizedRoleName` method of the `org.a11y.atspi.Accessible` interface. Make use of `AtspiRole::Extended` if a value is supplied, as it is the only way to tell libatspi to query it. Orca still won't announce it because it currently explicitly ignore this role, Accerciser however displays it properly.
Tested on all platforms by modifying the winit example.
> feat: Support custom role descriptions

- .github/workflows/c-bindings.yml
- .github/workflows/ci.yml
- .github/workflows/python-bindings.yml
- Cargo.lock
- Cargo.toml
- README.md
- bindings/python/.cargo/config.toml
- bindings/python/Cargo.toml
- bindings/python/README.md
- bindings/python/examples/pygame/.gitignore
- bindings/python/examples/pygame/README.md
- bindings/python/examples/pygame/hello_world.py
- bindings/python/examples/pygame/requirements.txt
- bindings/python/src/common.rs
- bindings/python/src/geometry.rs
- bindings/python/src/lib.rs
- bindings/python/src/macos.rs
- bindings/python/src/unix.rs
- bindings/python/src/windows.rs
- pyproject.toml
- release-please-config.json
Adds a new crate containing bindings for the Python programming language.
Wheels will be automatically uploaded to `pypi.org` for the most common platforms/architectures.
The pygame example is on par with the SDL example, except for Linux where hit-testing is probably not possible due to pygame not exposing window real size.
I'm not 100% sure about the unsendable types: is it enough to just document the fact that they must only be used from the main thread? Or should we protect users more?
> feat: Add Python bindings

- .github/workflows/c-bindings.yml
I used to use a different GitHub action to push assets to a release which required the URL to the release. This information is only provided to workflows on release events.
However, AButler/upload-release-assets only require the tag, so we can use the push tag event just fine.
This avoids starting a workflow for every crate release, having them all skipped except for accesskit_c.
> ci: Run C bindings workflow only on accesskit_c tag push

- .github/workflows/ci.yml
- .github/workflows/python-bindings.yml
- bindings/python/Cargo.toml
- bindings/python/examples/pygame/README.md
- pyproject.toml
All these changes are to better align with [kivy](https://github.com/kivy/kivy)'s build matrix. The only missing target is ARMv6L, but it isn't supported by Rust.
We could also build for apple-universal2 instead of x86_64 and aarch64 separately. Cargo doesn't support this but maturin has a special post-linking step for it.
Given the nature of the changes, I don't think accesskit_python's semver should be increased.
> fix: Decrease minimum Python version to 3.8 for Python bindings

- Cargo.lock
- platforms/unix/Cargo.toml
- platforms/unix/src/adapter.rs
- platforms/unix/src/context.rs
I noticed that we can get rid of a couple of async-related crates when the `tokio` feature is enabled, because tokio ships its own async types.
> fix: Make full use of the tokio ecosystem if the `tokio` feature is enabled on Unix

- Cargo.lock
- bindings/c/Cargo.toml
- bindings/python/Cargo.toml
- platforms/unix/Cargo.toml
- platforms/windows/Cargo.toml
- platforms/winit/Cargo.toml
As reported by `cargo deny check advisories`.
Updated crates:
- hermit-abi
- wasm-bindgen
- zerocopy: [security advisory](https://github.com/advisories/GHSA-rjhf-4mh8-9xjq)
I haven't manually updated `Cargo.toml` for the following workspace members because I don't think they are impacted, please double-check:
- common
- consumer
- platforms/macos
> fix: Update yanked dependencies

- platforms/unix/src/adapter.rs
For some reason it only showed up when I ran clippy for Rust 1.68.2.
> chore: Fix a clippy warning in the Unix adapter

- platforms/windows/examples/hello_world.rs
- platforms/winit/examples/simple.rs
The `CARGO_BIN_NAME` environment variable is passed to example binaries starting from Rust `1.69`. By getting rid of these we can still compile on `1.68.2` (which is the lowest version we can compile the rest of the workspace with).
> chore: Don't read environment variables inside the examples anymore

- platforms/windows/src/subclass.rs
This prevents clippy from being the limiting factor in our MSRV. The MSRV for `accesskit_windows` is now 1.64.0 with or without clippy.
> fix: Avoid `unnecessary_literal_unwrap` clippy lint

- Cargo.toml
- bindings/c/Cargo.toml
- bindings/python/Cargo.toml
- common/Cargo.toml
- consumer/Cargo.toml
- platforms/macos/Cargo.toml
- platforms/unix/Cargo.toml
- platforms/windows/Cargo.toml
- platforms/winit/Cargo.toml
- The `authors` key has been sort of deprecated for a while now, but I kept this change in a separate commit so we can easily revert it if we don't agree.
- I have everything ready to enforce our MSRV, but `1.68.2` isn't the correct value at this time:
- We read the `CARGO_BIN_NAME` environment variables in some examples, which is only supported since `1.69`.
- We allow the `unnecessary_literal_unwrap` in `platforms/windows/src/subclass.rs` yet this clippy lint was introduced in `1.72`.
So we need to decide whether to replace the offending lines, or to bump our MSRV to `1.72`.
> chore: Use the `workspace.package` table for keys which apply to all of our crates

- .github/workflows/ci.yml
Blocked on #344 
Ensures that AccessKit can compile with the minimum Rust version as advertised in the workspace's `Cargo.toml`.
`cargo clippy` deliberately runs on stable so we can allow/deny lints that are not present on older Rust versions.
> ci: Enforce MSRV

- platforms/unix/src/adapter.rs
All state-related events are already taken care of by `PlatformNode::notify_state_changes`. Firing these events twice often make Orca fail to announce when text input nodes get the focus.
> fix: Don't emit focus events twice on Unix

- platforms/atspi-common/README.md
I realized that I can't actually publish `accesskit_atspi_common` to crates.io because I didn't add the README.
> fix: Add missing README

- Cargo.lock
- platforms/windows/Cargo.toml
- platforms/windows/examples/hello_world.rs
- platforms/windows/src/node.rs
- platforms/windows/src/tests/mod.rs
- platforms/windows/src/text.rs
- platforms/windows/src/util.rs
Closes #350 
I don't think we can do more than that.
> fix: Bump windows-rs dependency to 0.52

- common/src/lib.rs
This simple fix is necessary for the upcoming refactor of `accesskit_consumer` to use `immutable-chunkmap` to bring back full copy-on-write tree snapshots.
> fix: Derive `PartialOrd` and `Ord` on `NodeId`

- Cargo.lock
This doesn't actually affect us since the vulnerability is Windows-specific, and we only rely on tokio on *nix platforms.
See the advisory for [RUSTSEC-2024-0019](https://rustsec.org/advisories/RUSTSEC-2024-0019).
> fix: Update mio dependency to address RUSTSEC-2024-0019

- common/src/lib.rs
This just makes it a bit more obvious which `Role` is the default, as it's now written near the actual variant.
> refactor: Use `#[default]` attribute macro on `Role`

- common/src/lib.rs
Per https://github.com/AccessKit/accesskit/pull/344#issuecomment-1898783756
It allows us to get rid of an `Option` and a few calls to `Option::unwrap`.
> fix: Make `NodeClassSet::new` const

- consumer/src/text.rs
I'm not surprised that this already worked with my UTF-16 index conversion functions. But we need to make sure we cover this case in new code, e.g. the upcoming AT-SPI text support.
> test: Add combining characters to the text tests

- platforms/atspi-common/src/adapter.rs
I need this in my `newton_atspi_compat` crate so I can create a `PlatformNode` from the window root outside of the AT-SPI event handler._
> fix: Expose root node ID in `accesskit_atspi_common::Adapter`

- Cargo.lock
- platforms/windows/Cargo.toml
- platforms/windows/src/adapter.rs
- platforms/windows/src/node.rs
- platforms/windows/src/tests/simple.rs
- platforms/windows/src/text.rs
- platforms/windows/src/util.rs
The major highlight of this PR is that `VariantFactory` is replaced by a simpler `Variant` newtype. The `VARIANT` type from the `windows` crate is used directly whenever possible.
> fix: Update `windows` to `0.54`

- platforms/macos/src/subclass.rs
The compiler is now issuing a warning about taking a reference to a mutable static; this will become a hard error in the 2024 edition.
> fix: Fix new compiler warning in Rust 1.77

- bindings/c/src/lib.rs
Unclear why this wasn't caught by our CI, running clippy on the workspace spits out a warning.
> fix: Remove unused `BoxCastPtr::set_mut_ptr` in the C bindings

- bindings/c/README.md
- bindings/c/accesskit-config.cmake
- bindings/c/examples/sdl/CMakeLists.txt
- bindings/c/examples/windows/CMakeLists.txt
The Meson build system needs this in order to find the header file. I encountered this problem while working on integrating AccessKit into GTK. Our current build system may not work for distro packagers, but this fix at least lets me make progress on that project, and may also help other users.
> fix: Set INTERFACE_INCLUDE_DIRECTORIES in CMake config

- consumer/src/node.rs
- consumer/src/tree.rs
- platforms/atspi-common/src/node.rs
- platforms/macos/src/node.rs
- platforms/windows/src/node.rs
I know at least Slint implements it.
There is apparently no corresponding event to fire on macOS. Also on this platform: Chromium includes it in live region updates, but we don't do that on other platforms so this must be a Chromium specific thing.
Tested on all platforms by modifying the winit example like so:
```rust
fn build_button(id: NodeId, name: &str, classes: &mut NodeClassSet) -> Node {
let rect = match id {
BUTTON_1_ID => BUTTON_1_RECT,
BUTTON_2_ID => BUTTON_2_RECT,
_ => unreachable!(),
};
let mut builder = NodeBuilder::new(Role::Button);
builder.set_bounds(rect);
builder.set_name(name);
builder.set_description("Announces that this button was pressed.");
builder.add_action(Action::Focus);
builder.set_default_action_verb(DefaultActionVerb::Click);
builder.build(classes)
}
```
> feat: Implement the `description` property

- Cargo.lock
- platforms/macos/Cargo.toml
- platforms/macos/src/adapter.rs
- platforms/macos/src/context.rs
- platforms/macos/src/event.rs
- platforms/macos/src/lib.rs
- platforms/macos/src/node.rs
- platforms/macos/src/patch.rs
- platforms/macos/src/subclass.rs
- platforms/macos/src/util.rs
`icrate` has been split into multiple smaller crates, and the feature setup in that has been reworked, which should improve compilation times.
> Use new objc2 crates

- bindings/c/examples/sdl/hello_world.c
- bindings/c/examples/windows/hello_world.c
- bindings/c/src/common.rs
- bindings/c/src/lib.rs
- bindings/python/examples/pygame/hello_world.py
- bindings/python/src/common.rs
- bindings/python/src/lib.rs
- common/src/lib.rs
- consumer/src/lib.rs
- consumer/src/node.rs
- consumer/src/text.rs
- consumer/src/tree.rs
- platforms/macos/src/adapter.rs
- platforms/windows/examples/hello_world.rs
- platforms/windows/src/adapter.rs
- platforms/windows/src/tests/simple.rs
- platforms/windows/src/tests/subclassed.rs
- platforms/winit/examples/mixed_handlers.rs
- platforms/winit/examples/simple.rs
I now believe that this was a bad API design decision on my part. The original rationale was explained in a [blog post on optimizing node size](https://accesskit.dev/dramatically-reducing-accesskits-memory-usage/), but I now think I went too far. It's not at all clear from real-world measurements that this approach to minimizing node size at the cost of speed and API complexity is worth it. I mention speed because, of course, it takes time to determine whether the node class can be shared, by comparing the new node class with existing entries in the `BTreeSet`, and this is done every time `NodeBuilder::build` is called. And even if we eventually gather data showing that the size versus speed tradeoff is worthwhile, I think it was a mistake on my part to expose this complexity in the API. …
> refactor!: Drop `NodeClassSet`

- bindings/c/src/common.rs
- bindings/python/src/common.rs
- common/src/lib.rs
I thoughtlessly copied the original name from Chromium nearly 3 years ago. I can think of no good reason for that long, cumbersome name, and it's an API wart that I definitely don't want to ship in 1.0. The equivalent ARIA property is simply called `aria-level`. If we need to clarify the meaning of "level", the place to do that is in the docs, not the name.
> refactor!: Rename `hierarchical_level` to `level`

- common/src/lib.rs
This continues the pattern of eliminating states that don't have a clear meaning. In this case, according to the MDN documentation for `aria-sort`, the default value for that ARIA property is `none`. This means that specifying `aria-sort="none"` is synonymous with not specifying it at all. So, like other AccessKit enums such as `AutoComplete`, I think it's best to not have a `None` value, which is what `SortDirection::Unsorted` really is; instead, the user just shouldn't set the property at all.
> refactor!: Drop `SortDirection::Unsorted`

- consumer/src/node.rs
- platforms/windows/src/node.rs
As far as I know, only UIA on Windows has such a property. But this simple feature is helping me debug my GTK AccessKit integration, since it makes it easy to find the GTK class of any accessible object, e.g. via NVDA+F1.
> feat: Expose the class name property

- bindings/c/src/common.rs
- bindings/python/src/common.rs
- common/src/lib.rs
This is a standard ARIA relation, so I'm surprised we didn't already inherit it from Chromium; I doubt I would have deliberately left it out or removed it. Anyway, I noticed it while going through the relations in GTK.
> feat: Add the `owns` relation

- Cargo.lock
- platforms/windows/Cargo.toml
- platforms/windows/src/tests/subclassed.rs
- platforms/winit/Cargo.toml
- platforms/winit/examples/mixed_handlers.rs
- platforms/winit/examples/simple.rs
- platforms/winit/src/lib.rs
Examples now use the new `ApplicationHandler` trait, which led to significant changes.
This is a breaking change to `accesskit_winit`, as described in the [changelog](https://docs.rs/winit/latest/winit/changelog/index.html).
> fix!: Update winit to 0.30

- platforms/unix/Cargo.toml
This dummy commit is necessary to force `accesskit_unix` to have a new semver-major version number, since all of the previous breaking changes never actually touched the code of this crate.
> fix!: Force a semver-breaking release

- platforms/atspi-common/src/node.rs
Applies the `pub(crate)` visibility qualifier to all methods of this type to make it clear that none are publicly accessible.
> refactor: Fix `accesskit_atspi_common::NodeWrapper` methods visibility

- bindings/c/src/lib.rs
- bindings/python/src/common.rs
This is causing CI to fail in another PR, now that Rust 1.78 has added a new dead code warning for trait associated functions.
> fix: Fix dead code warning on Unix platforms

- platforms/windows/src/adapter.rs
- platforms/windows/src/context.rs
- platforms/windows/src/node.rs
- platforms/windows/src/text.rs
On Windows, when running the winit simple example, which uses the placeholder tree, I noticed that with both NVDA and Narrator, the screen reader would sometimes not announce the new window, and if you queried the current focus, it would announce whatever had focus before. The cause seems to be that when transitioning from the placeholder tree to the real tree, a new context is created, and the placeholder context is discarded. That means that if the screen reader previously had a reference to the root node in the placeholder tree, that object would start returning `UIA_E_ELEMENTNOTAVAILABLE`.
I had thought that using a completely separate context for the placeholder tree was the cleanest solution. After all, we don't know what the root node ID of the real tree would be. So I figured, we …
> fix: Make the transition from placeholder to real tree more robust

- bindings/c/src/common.rs
I missed this inconsistency when I originally reviewed the C bindings.
> fix!: Rename `accesskit_builder_set_text_selection` to `accesskit_node_builder_set_text_selection`

- platforms/atspi-common/src/adapter.rs
- platforms/atspi-common/src/filters.rs
- platforms/atspi-common/src/node.rs
- platforms/macos/src/event.rs
- platforms/macos/src/filters.rs
- platforms/macos/src/node.rs
- platforms/windows/src/adapter.rs
- platforms/windows/src/filters.rs
- platforms/windows/src/node.rs
This is the other half of #365
> fix: Fix platform adapters to support copy-on-write tree snapshots again

- consumer/src/iterators.rs
This was broken when calling `preceding_filtered_siblings` or `following_filtered_siblings` on the only child of an ignored parent. I extended the tests to cover that case.
> fix: Fix the filtered sibling iterators to use the filtered parent to find the back node

- platforms/atspi-common/src/adapter.rs
- platforms/atspi-common/src/node.rs
I now believe that #354 was a mistake. So I've re-added the code in `focus_moved` to emit focus change events. But now, we specifically skip the focused state when looking for generic state changes. Reasons to do it this way:
1. If a node has just been added, whether actually added to the tree or just newly visible in the filtered tree, we don't generally want to emit state change events for that node, but if it's the focused node, we do have to emit a focus event.
2. If a node has other state changes at the same time that it receives focus, we want to emit the other state change events before the focus event. If we do it the other way around, as might happen depending on the order of the states, then Orca might read some states twice, once when presenting the newly focused node, and …
> fix: Return to handling focus events directly, after generic node changes

- consumer/src/iterators.rs
- consumer/src/lib.rs
- consumer/src/node.rs
I came across this while testing my GTK AccessKit implementation with a real GNOME app. We forgot to reset `consider_children` in the case where the filter result for the child is `ExcludeSubtree`. The new nodes I added to the test tree follow the same pattern as the nodes in the real app tree that triggered this bug.
> fix: Fix a logic error that sometimes caused filtered traversal to stop prematurely

- platforms/atspi-common/src/node.rs
Should have probably been included as part of #411 
We need to compare old filtered children with new filtered children in order to decide which ones were added and removed, otherwise we emit `object:children-changed:remove` events for nodes unknown to ATs.
> fix: Don't fire events for filtered children on Unix

- consumer/src/node.rs
- platforms/atspi-common/src/node.rs
- platforms/atspi-common/src/simplified.rs
- platforms/macos/src/node.rs
- platforms/unix/src/atspi/interfaces/accessible.rs
- platforms/windows/src/node.rs
The only notable difference with the Chromium implementation is the name of the attribute holding the value on Unix. Chromium uses `placeholder` as it is common with IAccessible2. I chose to use `placeholder-text` as that is what Orca checks first, and that is also what GTK uses.
Also worth mentioning that the AT-SPI "specification" says that we should fire `attribute-changed` events, but Chromium doesn't do it and I think it would be costly to rebuild the hashmap everytime once we'll start adding more attributes.
These changes were tested on all platforms with the example below:
<details><summary>platforms/winit/examples/placeholder.rs</summary>
<p>
```rust
use accesskit::{
Action, DefaultActionVerb, Node, NodeBuilder, NodeId, Rect, Role, Tree, TreeUpdate,
};
use …
```
> feat: Expose the `placeholder` property

- Cargo.lock
- consumer/Cargo.toml
accesskit_consumer now requires at least immutable-chunkmap 2.0.5 because that's the first version that doesn't depend on packed_struct and all of its transitive dependencies.
> fix: Update minimum version of immutable-chunkmap

- platforms/atspi-common/src/node.rs
- platforms/atspi-common/src/util.rs
Orca apparently changed the way it queries for bounds. Now only the client area of a window is considered. I chose to not drop the `WindowBounds::outer` field because we might need it again later, and it is public.
We also now support querying coordinates in relation to a parent, a feature that I haven't seen used but could be useful when dealing with text for instance.
> fix: Improve how coordinates are computed on Unix

- consumer/src/node.rs
- platforms/atspi-common/src/node.rs
- platforms/macos/src/node.rs
- platforms/windows/src/node.rs
- platforms/windows/src/util.rs
These changes were tested on all platforms with the example below:
<details><summary>platforms/winit/examples/orientation.rs</summary>
<p>
```rust
use accesskit::{
Action, DefaultActionVerb, Node, NodeBuilder, NodeId, Orientation, Rect, Role, Tree, TreeUpdate,
};
use accesskit_winit::{Adapter, Event as AccessKitEvent, WindowEvent as AccessKitWindowEvent};
use std::error::Error;
use winit::{
application::ApplicationHandler,
event::WindowEvent,
event_loop::{ActiveEventLoop, EventLoop, EventLoopProxy},
window::{Window, WindowId},
};
const WINDOW_TITLE: &str = "Orientation test";
const WINDOW_ID: NodeId = NodeId(0);
const HORIZONTAL_SCROLLBAR_ID: NodeId = NodeId(1);
const VERTICAL_SCROLLBAR_ID: NodeId = NodeId(2);
const INITIAL_FOCUS: NodeId = WINDOW_ID;
const HORIZONTAL_SCROLLBAR_RECT: Rect …
```
> feat: Expose the `orientation` property

- platforms/atspi-common/src/adapter.rs
To reproduce the bug, add two newlines to the end of an empty multi-line edit control. When the second newline is added, the old text will be "\n" and the new text will be "\n\n". Before this fix, the function mistakely calculated 1 byte as a common suffix since both strings ended with a newline, even though that same newline in the old string was also the common prefix.
> fix: Fix a logic error in suffix calculation for text changes

- consumer/src/text.rs
Relates to #416 
Given an egui multiline text area, there is another way to get a panic, as reported to me by a Linux user:
- Write "Hello",
- Press the Enter key twice,
- Write "world",
- Press the up arrow to place the caret on the empty line.
This fix makes `Node::text_selection_focus` consistent with `Node::text_selection` and prevents panicking, but doesn't fix the underlying issue in egui, as "world" is now announced instead of "blank".
> fix: Clamp character index when getting focus from a text selection

- bindings/c/src/common.rs
- bindings/python/src/common.rs
- common/src/lib.rs
- consumer/src/node.rs
- platforms/atspi-common/src/node.rs
- platforms/atspi-common/src/simplified.rs
- platforms/macos/src/node.rs
- platforms/unix/src/atspi/interfaces/accessible.rs
- platforms/windows/src/node.rs
- platforms/winit/Cargo.toml
Adds a new optional `author_id` property, useful primarily for QA.
- On Unix: the purpose of the `AccessibleId` property have been clarified since I wrote the adapter. These changes make it behave like GTK4.
- On macOS: I haven't really found other implementations of this property, but Apple documentation indicates that `accessibilityIdentifier` is intended for this.
Tested on Windows and Linux by modifying the `mixed_handlers` example like so:
```rust
diff --git a/platforms/winit/examples/mixed_handlers.rs b/platforms/winit/examples/mixed_handlers.rs
index 00281e2..7c1e68f 100644
--- a/platforms/winit/examples/mixed_handlers.rs
+++ b/platforms/winit/examples/mixed_handlers.rs
@@ -43,8 +43,14 @@ fn build_button(id: NodeId, name: &str) -> Node {
BUTTON_2_ID => BUTTON_2_RECT,
_ => …
```
> feat: Add `author_id` property

- bindings/c/examples/sdl/hello_world.c
- bindings/c/examples/windows/hello_world.c
- bindings/c/src/common.rs
This is the simplest way to allow C API users, like GTK, to asynchronously handle arbitrary action requests on another thread.
> refactor!: Transfer ownership of action requests in the C API

- platforms/atspi-common/src/adapter.rs
This is necessary if a large number of nodes have changed in a large document, but the text itself hasn't changed. That currently happens when scrolling GtkTextView, and while I could probably optimize that specific case somehow, this optimization is easier and, as far as I can tell, doesn't break anything.
> fix: Avoid unnecessary repeated checks for text changes

- platforms/atspi-common/Cargo.toml
- platforms/atspi-common/src/lib.rs
- platforms/unix/Cargo.toml
Most users don't actually need this, they should not have to compile it. I'm not set on the name of the feature, feel free to suggest something else.
> feat: Feature-gate the `accesskit_atspi_common::simplified` module

- bindings/c/examples/sdl/hello_world.c
- bindings/c/examples/windows/hello_world.c
- bindings/python/examples/pygame/hello_world.py
- common/src/lib.rs
- consumer/src/iterators.rs
- consumer/src/lib.rs
- consumer/src/node.rs
- consumer/src/text.rs
- platforms/atspi-common/src/node.rs
- platforms/macos/src/node.rs
- platforms/unix/Cargo.toml
- platforms/windows/examples/hello_world.rs
- platforms/windows/src/node.rs
- platforms/winit/examples/mixed_handlers.rs
- platforms/winit/examples/simple.rs
The term "static text" is archaic; it goes back to the early days of Windows and, if I remember correctly, the original Macintosh Toolbox. But every modern GUI toolkit I can think of, as far back as Java's AWT in the 90s, refers to this type of object as a label, whether or not it's actually labeling another control. To achieve our goal of making accessibility approachable to today's developers, we should eliminate unfamiliar and archaic terminology wherever we can. So, while this is another inconvenience for our early adopters, I think this name change is worthwhile.
Also, I now believe that the role that we used to call static text, that we now call label, should map to the AT-SPI label role, not the AT-SPI static role. This is based on what I see in both GTK 3 and 4, which use the …
> refactor!: Rename the static text role to label

- consumer/src/filters.rs
- platforms/atspi-common/src/adapter.rs
I discovered that this was a problem when testing a GTK app with the actual AT-SPI adapter. Attempting to unregister the interfaces for a removed node resulted in a D-Bus error saying that the Accessible interface hadn't been registered in the first place. The problem was that the node wasn't registered in the first place, since its parent had the `hidden` flag set, meaning that the parent's filter result was `ExcludeSubtree`. But when the node was removed, its filter result was `Include`, since calling `filter` on the node didn't check the parent, and the node itself didn't have the `hidden` flag set.
So now, `common_filter` checks the parent.
I added `add_subtree` and `remove_subtree` because a callback to `node_updated` on a single node can indicate a change in the visibility of the …
> fix: Correctly handle recursive filtering

- consumer/src/node.rs
Since we already have an implicit labelled-by relationship for buttons and links, I think it makes sense to extend it to more parent roles where it should obviously apply. I realized the need for this when I tried a Xilem example with NVDA and discovered that while Xilem assumes that the implicit relationship applies to check boxes, it actually didn't.
> fix: Extend the implicit labelled-by relation to more parent roles

- consumer/src/node.rs
- consumer/src/tree.rs
I think it's reasonable to only add a given action to a node if that action does something meaningful in the node's current state. And we may want to recommend that. But things like the UIA `IsKeyboardFocusable` property and the AT-SPI focusable state should be set even when the node is already focused, so the node might not have the `Focus` action in that state.
One subtlety: I added a helper, `is_focused_in_tree`, to check whether the node is focused within the tree, regardless of whether the host (e.g. window) is focused. If the node is focused in the tree, then the node might not have the `Focus` action, regardless of whether the host is focused.
> fix: `Node::is_focusable` always returns true if the node is focused

- common/src/lib.rs
Consider this program:
```rust
use accesskit::{Action, DefaultActionVerb, NodeBuilder, Rect, Role};
fn main() {
let rect = Rect {
x0: 0.0,
y0: 0.0,
x1: 50.0,
y1: 200.0,
};
let mut builder = NodeBuilder::new(Role::Button);
builder.set_bounds(rect);
builder.set_name("Send");
builder.set_busy();
builder.add_action(Action::Focus);
builder.set_default_action_verb(DefaultActionVerb::Click);
println!("{builder:?}");
let node = builder.build();
println!("{node:?}");
}
```
This currently outputs:
```
NodeBuilder { role: Button, actions: 2, flags: 64, properties: PropertiesBuilder { indices: PropertyIndices([84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 1, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, 84, …
```
> fix: Improve debug representation of `Node` and `NodeBuilder`

- platforms/unix/src/atspi/bus.rs
- platforms/unix/src/atspi/interfaces/accessible.rs
- platforms/unix/src/atspi/interfaces/mod.rs
- platforms/unix/src/atspi/object_address.rs
- platforms/unix/src/atspi/object_id.rs
AT-SPI's documentation clarified this since I first implemented the Unix adapter: the root/application node's parent is not the desktop object but a null reference, and the bus name component of an object reference is an empty string.
> fix: Return a null object for AT-SPI application's parent

- CONTRIBUTING.md
- Cargo.toml
- common/Cargo.toml
- consumer/Cargo.toml
- platforms/atspi-common/Cargo.toml
- platforms/macos/Cargo.toml
- platforms/unix/Cargo.toml
- platforms/windows/Cargo.toml
- platforms/winit/Cargo.toml
Blocks #456 
We have been stuck on zbus 3 for quite a while now because of this. I think this change won't impact our users at this point, therefore waiting longer would only hurt AccessKit adoption.
> fix: Update minimum supported Rust version to 1.75

- Cargo.lock
- platforms/atspi-common/Cargo.toml
- platforms/unix/Cargo.toml
- platforms/unix/src/atspi/interfaces/accessible.rs
- platforms/unix/src/atspi/interfaces/action.rs
- platforms/unix/src/atspi/interfaces/application.rs
- platforms/unix/src/atspi/interfaces/component.rs
- platforms/unix/src/atspi/interfaces/text.rs
- platforms/unix/src/atspi/interfaces/value.rs
- platforms/unix/src/atspi/object_address.rs
- platforms/unix/src/lib.rs
This also requires bumps to
* atspi        v0.19 -> v0.22
* atspi-common v0.3  -> v0.6
* zbus         v3.14 -> v4.4
* zvariant     v3    -> v4.2
This is motivated by wanting to reduce the amount of dependencies on `syn` v1.
> fix: update to ZBus v4

- common/src/lib.rs
Since using accesskit `0.16.2` the following issue appears when enabling the `enumn` feature
```shell
error[E0592]: duplicate definitions with name `n`
--> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/accesskit-0.16.2/src/lib.rs:270:38
|
270 | #[cfg_attr(feature = "enumn", derive(enumn::N))]
|                                      ^^^^^^^^ duplicate definitions for `n`
...
349 |     fn n(value: u8) -> Option<Self> {
|     ------------------------------- other definition for `n`
|
= note: this error originates in the derive macro `enumn::N` (in Nightly builds, run with -Z macro-backtrace for more info)
error[E0034]: multiple applicable items in scope
--> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/accesskit-0.16.2/src/lib.rs:386:39
|
386 | …
```
> fix duplicate definitions

- platforms/macos/src/node.rs
- platforms/winit/examples/simple.rs
* Updated macos adapter to work better with the Xcode Accessibility Inspector, by providing `accessibilityWindow` and `accessibilityTopLevelUIElement` selectors. 
Before:
https://github.com/user-attachments/assets/3211f50c-9f35-4a43-9575-21a1ab50b9e3
After:
https://github.com/user-attachments/assets/f5c42461-8f1d-48bb-94e6-355921869425
The behaviour of VoiceOver has not changed, and reads out the same as before.
> Xcode Accessibility Inspector update for the macOS adapter

- common/Cargo.toml
- common/src/geometry.rs
- common/src/lib.rs
- consumer/Cargo.toml
- platforms/atspi-common/Cargo.toml
- platforms/macos/Cargo.toml
- platforms/unix/Cargo.toml
- platforms/windows/Cargo.toml
- platforms/winit/Cargo.toml
This is a prerequisite for eventually implementing accessibility for toolkits in embedded environments, such as those supported by Slint. And I don't think it's too drastic a change for the potential benefits.
The next step is to make `accesskit_consumer` no-std. That depends on estokes/immutable-chunkmap#10.
It's a breaking change because I had to drop the `Affine::rotate` method, which depends on a math function that's not in core. I don't think that's really a problem; I've never used that method. And anyway, this is more of a feature than a fix. And I have more breaking changes planned for this next release cycle.
This also adds the usual dummy changes to force the proper version number bump for the downstream crates.
> feat!: Make the core crate no-std

- common/src/lib.rs
- consumer/src/node.rs
- platforms/atspi-common/src/node.rs
- platforms/macos/src/node.rs
- platforms/windows/examples/hello_world.rs
- platforms/windows/src/node.rs
- platforms/winit/examples/mixed_handlers.rs
- platforms/winit/examples/simple.rs
I don't even remember the precise distinction between `Action` and `DefaultActioNVerb`, or the rationale for adding a given action to one and not the other; it was just something I copied from Chromium. So I've decided to simplify the model. Having an accessible action called `Click` might displease some pedants, but it should be more familiar to GUI toolkit developers, especially those who are familiar with the `click` event in the web DOM.
> refactor!: Drop `DefaultActionVerb`

- common/src/lib.rs
- consumer/src/filters.rs
- consumer/src/text.rs
- platforms/atspi-common/src/adapter.rs
- platforms/atspi-common/src/node.rs
- platforms/macos/src/event.rs
- platforms/macos/src/node.rs
- platforms/windows/src/adapter.rs
- platforms/windows/src/node.rs
I copied "inline text box" from Chromium. But "text run" will be more familiar to anyone who has worked on a modern text layout implementation. And it's shorter.
> refactor!: Rename `Role::InlineTextBox` to `TextRun`

- platforms/macos/src/node.rs
Added isAccessibilityEnabled to MacOS adapter.
This is based on the is_disabled attribute from the consumer crate.
If an accessibility node is explicitly set to disabled, it is marked as disabled on the MacOS accessibility node.
Otherwise it is marked as enabled.
When read out by VoiceOver, the item is read as "dimmed".
https://github.com/user-attachments/assets/89286e40-c532-465a-a39f-14294da3ac60
> Add isEnabled to MacOS adapter

- common/src/lib.rs
- consumer/src/lib.rs
- consumer/src/node.rs
- consumer/src/text.rs
- consumer/src/tree.rs
- platforms/macos/src/adapter.rs
- platforms/windows/examples/hello_world.rs
- platforms/windows/src/adapter.rs
- platforms/windows/src/tests/simple.rs
- platforms/windows/src/tests/subclassed.rs
- platforms/winit/examples/mixed_handlers.rs
- platforms/winit/examples/simple.rs
By doing this, passing the new `Node` (former `NodeBuilder`) in `TreeUpdate`, and having the consumer convert to the slightly smaller `FrozenNode`, we make the API more convenient for all users while not giving up the node size optimization. And it's probably slightly better for binary size to do the conversion to `FrozenNode` in just one place.
> refactor!: Rename `NodeBuilder` to `Node` and the old `Node` to `FrozenNode`

- common/src/lib.rs
- consumer/src/lib.rs
- consumer/src/node.rs
- consumer/src/tree.rs
- platforms/atspi-common/src/node.rs
- platforms/macos/src/event.rs
- platforms/macos/src/node.rs
- platforms/windows/examples/hello_world.rs
- platforms/windows/src/adapter.rs
- platforms/windows/src/node.rs
- platforms/windows/src/tests/simple.rs
- platforms/windows/src/tests/subclassed.rs
- platforms/winit/examples/mixed_handlers.rs
- platforms/winit/examples/simple.rs
I think the new property name and the new use of `value` on nodes with `Role::Label` makes sense because:
* For non-label nodes, their label is now determined by either a direct string in the `label` property, or the `labelled_by` relation. The word choice is more consistent.
* On a label itself, it doesn't make sense to talk about the "label of a label", but "value of a label" does make sense.
* For labels that have full text support via `TextRun` nodes, we can now automatically get the label's value from its descendant text runs, rather than having to set the value directly; this follows automatically from the existing support for constructing the value from text in `accesskit_consumer::Node::value`.
> refactor!: Rename `name` to `label` and use `value` for label content

- common/README.md
This was pointed out to me by a game developer who is considering adding AccessKit to their game.
> chore: Mention all adapters in common crate's README

- common/src/lib.rs
As @DataTriny points out, Chromium does nothing with this property in any of its backends for modern accessibility APIs. There was a state flag for it in MSAA, but we don't implement MSAA. And it's easy enough for an AT to calculate this state itself by looking at the cursor position.
> fix!: Drop the `is_hovered` property

- Cargo.lock
- consumer/Cargo.toml
- consumer/src/iterators.rs
- consumer/src/lib.rs
- consumer/src/node.rs
- consumer/src/text.rs
- consumer/src/tree.rs
- deny.toml
I think the only potentially controversial part of this is the decision to switch from hash tables to B-trees for the temporary data structures that are built while processing an update. Here's my reasoning.
`HashMap` and `HashSet` aren't in `alloc` because the default hasher requires entropy. We could add a `std` feature to `accesskit_consumer` and then bring in `hashbrown` as a dependency only when `std` is disabled. But for simplicity, I'd rather not add an extra feature and different code paths if we can avoid it.
I don't like depending on a random number generator anyway, even when using `std`. Predictability is a valuable attribute in software, and I think it's worth maximizing it at as many levels of the stack as possible. Also, at least on Windows, using the random number …
> feat: Make the consumer crate no-std

- platforms/windows/Cargo.toml
Currently, [docs.rs fails to build accesskit_windows](https://docs.rs/crate/accesskit_windows/latest).
I tried documenting the crate on Linux and I get the same compilation errors. I think that this crate now only builds on Windows so we need to tell docs.rs about this. We might want to investigate why this breakage happened later, and if we still want this crate to build on non-Windows platforms.
During investigation, I found broken links in our common crate, I'll deal with them in another PR.
> fix: Tell docs.rs to only build accesskit_windows on Windows

- consumer/src/tree.rs
We can avoid a few reallocations when applying tree updates to the tree. We know how many `NodeId`s we will add into `seen_child_ids` ahead of time, so use this information to reserve enough space to hold them.
> fix: Avoid reallocations when processing tree updates

- Cargo.lock
- platforms/macos/Cargo.toml
- platforms/macos/src/context.rs
- platforms/macos/src/event.rs
- platforms/macos/src/subclass.rs
- platforms/windows/Cargo.toml
- platforms/windows/src/adapter.rs
I planned to do this after I changed `accesskit_consumer` to use `hashbrown`. I haven't bothered to do this for `accesskit_atspi_common` or `accesskit_unix`, since interoperability with zbus is a concern for these crates, and the cumulative binary size of the Unix adapter is already quite big.
Also, for the macOS adapter, I decided that using a hash table to keep track of view subclasses was overkill, since the number of items will always be small, and lookup will be rare. So I decided to favor simplicity and minimal code size instead, by using a `Vec` with linear search. The other reason to revisit this was to eliminate the dependency on `once_cell`.
> fix: Optimize use of hash tables in platform adapters

- Cargo.lock
- Updates tempfile (`cargo update tempfile`), which removes dependency on the instant crate, which fixes [RUSTSEC-2024-0384](https://rustsec.org/advisories/RUSTSEC-2024-0384).
- Updates num_enum (`cargo update num_enum`) which removes an older version of hashbrown from the dependency tree.
- Updates hashbrown (`cargo update hashbrown`) which fixes [RUSTSEC-2024-0402](https://rustsec.org/advisories/RUSTSEC-2024-0402).
Clippy fixes will come in a separate PR.
> chore: Update some dependencies to fix potential vulnerabilities

- consumer/src/tree.rs
This eliminates an unnecessary step involving temporary storage. I originally wrote that code when I was still quite new to Rust and never revisited the assumption that `to_remove` was unnecessary.
I also renamed the variable that tracks unreachable nodes and the function that traverses them.
> fix: Optimize removal of unreachable nodes

- consumer/src/tree.rs
This eliminate intermediate allocations as well as some code duplications between the two branches of the old implementation. And in builds where panic messages aren't printed at all (e.g. using the unstable `build-std` and `panic_immediate_abort` features), the new design allows the code for constructing the truncated node ID list to be completely dropped.
In a normal size-optimized release build on x64 with `panic = "abort"`, this saves 2.5 KB of object code. In a `panic_immediate_abort` build (of the Windows `hello_world` example), this saves 4 KB.
> fix: Optimize the "short node list" helper used in panic messages

- common/src/lib.rs
- consumer/src/tree.rs
- platforms/atspi-common/src/adapter.rs
- platforms/atspi-common/src/context.rs
- platforms/atspi-common/src/node.rs
- platforms/macos/Cargo.toml
- platforms/unix/src/context.rs
- platforms/windows/examples/hello_world.rs
- platforms/windows/src/node.rs
- platforms/windows/src/util.rs
- platforms/winit/examples/mixed_handlers.rs
- platforms/winit/examples/simple.rs
I now believe this property was a mistake.
On platforms where assistive technologies have conditional behavior based on the app name, they should get the app name from the platform, not the app itself. This way, correct behavior isn't dependent on the app or toolkit exposing the app name, and we don't give the app the opportunity to lie about its name.
Yes, AT-SPI requires the app to provide its own app name. I consider that a flaw in AT-SPI, which we should work around in the Unix adapter, rather than perpetuating it in our new cross-platform API. In Newton (the new free desktop accessibility stack I prototyped earlier this year), I want ATs to get the app name from the compositor, not the app itself, though I didn't implement that yet.
While I was here, I changed the `toolkit_name` and …
> refactor!: Drop `Tree::app_name`

- consumer/src/node.rs
- platforms/atspi-common/src/node.rs
- platforms/macos/src/node.rs
- platforms/windows/src/node.rs
I can't think of any reason why `role_description` and `placeholder` on `accesskit_consumer::Node` need to return an `Option<String>` rather than an `Option<&str>`. It just wastes an allocation, at least on Windows and macOS.
> refactor!: Optimize simple string getters

- consumer/src/node.rs
- consumer/src/text.rs
- platforms/windows/src/adapter.rs
- platforms/windows/src/node.rs
- platforms/windows/src/text.rs
- platforms/windows/src/util.rs
This reduces intermediate allocations, especially when dynamically building a label.
One could imagine taking advantage of this in a self-voicing adapter to write the label, value, or text range directly into the buffer that contains the utterance to be spoken, and that buffer could be reused across utterances.
On Windows, this allows us to construct the dynamic string as UTF-16 in one pass, rather than constructing it as UTF-8 and then re-encoding it to UTF-16 in another pass, adding a temporary allocation.
This change happens to add 512 bytes to the binary size of a `panic_immediate_abort` build of the Windows `hello_world` example on x86-64. It doesn't have any effect on the binary size of that same example built as a normal release build with `panic = "abort"`.
> fix: Optimize dynamic string building

- consumer/src/node.rs
- platforms/atspi-common/src/node.rs
- platforms/macos/src/node.rs
- platforms/windows/src/node.rs
This property is also used on Windows to indicate that an item must be selected from a listbox. This will come in a future PR.
Directly merging the two commits should properly update the version of the affected crates.
Tested with the following test program:
<details>
<summary>Test program source code</summary>
```rust
use accesskit::{Action, Node, NodeId, Rect, Role, Tree, TreeUpdate};
use accesskit_winit::{Adapter, Event as AccessKitEvent, WindowEvent as AccessKitWindowEvent};
use std::error::Error;
use winit::{
application::ApplicationHandler,
event::WindowEvent,
event_loop::{ActiveEventLoop, EventLoop, EventLoopProxy},
window::{Window, WindowId},
};
const WINDOW_TITLE: &str = "Test App";
const WINDOW_ID: NodeId = NodeId(0);
const TEXT_INPUT_ID: NodeId = NodeId(1);
const INITIAL_FOCUS: …
```
> Expose the `is_required` property

- Cargo.toml
This crate only make sense on *nix platforms (for now at least). By putting it in the list of default workspace members, we tell Cargo to build it on every platforms though. We can save some CI time by doing this since it is slow to build on Windows for instance.
> chore: Remove atspi-common from the default workspace members

- consumer/src/node.rs
- consumer/src/tree.rs
- platforms/atspi-common/src/adapter.rs
- platforms/atspi-common/src/context.rs
- platforms/atspi-common/src/util.rs
- platforms/macos/src/adapter.rs
- platforms/macos/src/context.rs
- platforms/macos/src/node.rs
- platforms/unix/src/adapter.rs
- platforms/windows/src/adapter.rs
- platforms/windows/src/context.rs
Derive the Debug trait for the unix platform adapter.
Side note, I now have [code](https://github.com/drewcrawford/app_window) in the wings that relies on my PRs.  I need to explore alternatives to relying on my patches landing here.
> fix: Derive `Debug` for adapters

- common/src/lib.rs
- consumer/src/node.rs
- platforms/atspi-common/src/adapter.rs
- platforms/atspi-common/src/events.rs
- platforms/atspi-common/src/node.rs
- platforms/atspi-common/src/simplified.rs
- platforms/macos/README.md
- platforms/macos/src/event.rs
- platforms/macos/src/node.rs
- platforms/unix/src/atspi/bus.rs
- platforms/unix/src/atspi/interfaces/mod.rs
- platforms/unix/src/atspi/interfaces/selection.rs
- platforms/windows/src/adapter.rs
- platforms/windows/src/node.rs
- platforms/windows/src/util.rs
Fixes #23 
Adds support for list box controls on all supported platforms.
VoiceOver only reports the selected items when the focus leaves the list box and if there is more than one child. I am not sure if this is the expected behavior for such controls. The `accessibilityRows` and `accessibilitySelectedRows` methods seem to never get called, but this might just be because of my very old macOS version.
These changes can be tested with [this fork of Slint](https://github.com/DataTriny/slint/tree/listview): `cargo run -p _7guis --bin crud`
The "Names" list view supports keyboard navigation: Up and Down arrows, PageUp, PageDown, Home and End keys, with the Control key modifier to move the focus but not the selection. However, multiple selections are not allowed. I think there are bugs in how …
> Add listbox support

- Cargo.lock
- platforms/unix/Cargo.toml
- platforms/unix/src/executor.rs
Fixes #515 
For simplicity, I chose to also drop the path to spawn a task using the unstable API. We'd have to enable the `tokio_unstable` flag ourself (previously done by zbus), just to name the task. Yes this would be useful in diagnozing a crash, but we don't test this enough for me to feel confident keeping this unstable code around.
Tested by running the winit example with both runtimes.
> fix: Don't enable the `zbus/tokio` feature on Unix

- Cargo.lock
- platforms/android/Cargo.toml
- platforms/windows/Cargo.toml
- platforms/windows/src/node.rs
This is an alternative to #527, using manual expansion of identifiers rather than another macro crate.
Fixes #526.
> fix: Eliminate the dependency on `paste`

- platforms/windows/src/subclass.rs
- platforms/winit/src/lib.rs
I've concluded that we have to enforce this rule in the most obnoxious way possible.
> fix!: Panic if the window is visible when the adapter is created, for adapters where this is a problem

- .github/dependabot.yml
I already have enabled Dependabot in this repository's settings.
> chore: Setup Dependabot to check for GitHub Actions updates

- .github/workflows/ci.yml
- deny.toml
Fixes #349 
The configuration differs from what we have in the C bindings:
- Some crates are skipped for now, the version requirement should help us notice when we can remove these exceptions.
- I have removed some Apple and Linux targets because it shouldn't be necessary to test them, unlike Windows where crates from windows-rs are architecture specific.
- The Android platform is added.
> chore: Update cargo deny configuration to prevent duplicate dependencies

- .github/workflows/ci.yml
- platforms/atspi-common/src/simplified.rs
I apparently forgot to compile atspi-common with all features when I did the zbus 5/atspi migration.
Since atspi-common is not a default member of the workspace, and since its simplified-api feature is not enabled by default, this was not caught by the CI. I've added a step in the clippy job to make sure it can compile.
> fix: Fix a compilation error in atspi-common `Event::new`

- .github/workflows/release-please.yml
The default GitHub token that is provided to the release-please workflow apparently doesn't permit triggering the CI on pull requests opened by release-please anymore. This might be linked to the permissions now set on the workflow.
Since we weren't using a token for a while now, I've edited the existing `RELEASE_PLEASE_TOKEN` secret. It now contains a personnal access token which belongs to the AccessKit organization and that can only write to this specific repository. This token is valid for a year.
> chore: Use a PAT for release-please

- Cargo.lock
- consumer/Cargo.toml
- consumer/src/node.rs
- consumer/src/tree.rs
I'm doing this because I want to minimize the temporary allocations that are needed when applying a tree update. Ideally, if the tree update doesn't add any new data, there should be zero temporary allocations; we should be able to reuse existing collections to apply the update in-place. Since our event handling is built around having a full, consistent snapshot of the tree before the update, and that is now quite a fundamental feature of our design, I've concluded that we need to keep two copies of the tree state at all times. So that means double the memory usage. I'm betting that in most cases, the application uses most of its memory on things other than the accessibility trees, and that on truly memory-constrained systems, the gains from having fewer temporary allocations (and thus …
> refactor!: Replace `immutable-chunkmap` with dual tree states

- Cargo.lock
- common/Cargo.toml
Addresses [RUSTSEC-2025-0020](https://rustsec.org/advisories/RUSTSEC-2025-0020)
Note that I didn't directly update to 0.24 in #512 because it brings more breaking changes, making the process of updating our Python bindings even more painful.
> fix: Update pyo3 to 0.24

- common/src/lib.rs
- consumer/src/node.rs
- consumer/src/tree.rs
If we decide to proceed in the direction started by #495, that is, minimizing temporary allocations when updating the tree at the cost of maintaining two copies of the tree state, then this PR is the next logical step. Dropping `FrozenNode` allows us to update nodes in place, including extending the `Vec` of properties, at the cost of 8 extra bytes per retained node (increasing the size from 120 to 128).
> refactor!: Drop `FrozenNode`

- Cargo.lock
Addresses [RUSTSEC-2025-0023](https://rustsec.org/advisories/RUSTSEC-2025-0023)
- `cargo update tokio-stream`
- `cargo update tokio`
For some reason, Cargo once again downgraded libloading's dependency on windows-targets so I had to revert this change.
> fix: Update tokio and tokio-stream dependencies

- common/src/lib.rs
- consumer/src/lib.rs
This state appears to only map to `STATE_SYSTEM_LINKED` on MSAA where it should be applied to nodes with `Role::Link` and their descendents, [according to the ARIA specification](https://www.w3.org/TR/core-aam-1.2/#role-map-link) and Chromium source code. I think we can safely ignore this property.
> refactor!: Drop unused `Node::is_linked`

- common/src/lib.rs
- consumer/src/tree.rs
We already represent node IDs in this way in our panic messages, so let's make this official. It is going to make reading debug representation of tree updates a bit easier.
> fix: Improve `NodeId`'s debug representation

- platforms/android/src/node.rs
`accesskit_consumer::Node::value` doesn't traverse a multiline input's descendants because we don't want to have the potential performance problem of traversing a large document every time a single character is typed. But I'm not aware of any other option on Android, so I changed the `text` method on `NodeWrapper` in the Android adapter.
> fix: Return text content from multiline inputs

- consumer/src/node.rs
- platforms/atspi-common/src/lib.rs
- platforms/atspi-common/src/node.rs
- platforms/atspi-common/src/simplified.rs
- platforms/macos/src/event.rs
- platforms/macos/src/node.rs
- platforms/unix/src/atspi/interfaces/accessible.rs
- platforms/windows/src/adapter.rs
- platforms/windows/src/node.rs
- platforms/windows/src/util.rs
Closes #28 
The following example program contains a tab bar with two tabs, one tab revealing a button and the other a checkbox.
<details>
<summary>platforms/winit/examples/tabs.rs</summary>
```rust
use accesskit::{
Action, ActionRequest, Node, NodeId, Orientation, Rect, Role, Toggled, Tree, TreeUpdate,
};
use accesskit_winit::{Adapter, Event as AccessKitEvent, WindowEvent as AccessKitWindowEvent};
use std::{error::Error, iter};
use winit::{
application::ApplicationHandler,
dpi::LogicalSize,
event::{ElementState, KeyEvent, WindowEvent},
event_loop::{ActiveEventLoop, EventLoop, EventLoopProxy},
keyboard::Key,
window::{Window, WindowId},
};
const WINDOW_TITLE: &str = "Tabs example";
const WINDOW_ID: NodeId = NodeId(0);
const TABLIST_ID: NodeId = NodeId(1);
const BUTTON_ID: NodeId = …
```
> Add support for tabs

- platforms/android/src/adapter.rs
It looks like the Android adapter isn't actually being built in CI. Let's fix that in a separate PR.
> fix: Fix Android adapter after dropping `FrozenNode`

- common/src/lib.rs
This covers 100% of the `lib.rs` file excluding lines related to serialization. The test suite also catches all mutants found by `cargo mutants` in this file, again excluding the serialization machinery.
> test: Add unit tests to the common crate

- platforms/unix/src/adapter.rs
See https://github.com/godotengine/godot/issues/106097
> fix: Mention caveats with window bounds under Wayland

- consumer/src/filters.rs
- consumer/src/node.rs
This exposes the scrolling and `clips_children` on the consumer `Node` struct. It also adds a new rule to the common filter to exclude clipped children, except for one clipped child at either end of a list (so that child can be scrolled into view).
> feat: Consumer support for scrolling and clipping children

- common/src/lib.rs
- platforms/atspi-common/src/node.rs
- platforms/atspi-common/src/simplified.rs
- platforms/atspi-common/src/util.rs
- platforms/macos/src/node.rs
- platforms/unix/src/atspi/interfaces/component.rs
- platforms/windows/src/node.rs
- platforms/windows/src/text.rs
The old `ScrollTarget` action data wasn't a good fit for what any platform actually supported. So I replaced it with a new `ScrollHint` which is a copy of Chromium's `ScrollType` enum, which in turn is a copy of AT-SPI's `ScrollType`.
The Windows implementation is known to work with Narrator, and the macOS implementation is known to work with VoiceOver. I don't know if there's any way to get Orca to call the `ScrollTo` method outside of web content. I know that NVDA doesn't call `ScrollIntoView` outside of web content. All of this can be tested using my [virtual-scroll-a11y branch of xilem](https://github.com/linebender/xilem/tree/virtual-scroll-a11y). That's actually still using the scrolling-wip branch of AccessKit, but it's the same code. I'll delete that branch after this PR is merged …
> feat!: Implement refactored `ScrollIntoView` action across desktop platforms

- Cargo.lock
- platforms/macos/src/subclass.rs
- platforms/windows/Cargo.toml
- platforms/windows/src/subclass.rs
- platforms/windows/src/tests/mod.rs
- platforms/windows/src/tests/subclassed.rs
> fix: Panic if the subclassing adapter is double-instantiated

- consumer/src/node.rs
- consumer/src/text.rs
It is currently necessary to set the `placeholder` property only if the text input it applies to is empty. This is what I did in Slint at the time but this is not how it was implemented in egui, resulting in some screen readers such as NVDA to report the placeholder and the value at the same time.
Following our philosophy of putting as much complexity into the adapters as possible, it is probably best to check for this invariant ourselves. This also aligns with ARIA.
> fix: Only expose the `placeholder` property on empty text inputs

- platforms/winit/src/lib.rs
> fix: Impl `Clone` and `PartialEq` on `WindowEvent`

- consumer/src/iterators.rs
Panics due to these calls to `Option::unwrap` have been reported multiple times already, only by Godot users as far as I can tell. I am not sure exactly under which circumstances such panics can occur, the most likely cause is if the iterator is advanced after it has returned `None` once.
> fix: Prevent filtered node iterators from panicking when exhausted
