AccessKit/accesskit

consumer/src/tree.rs
The cross-platform change tracking code now raises `NodeUpdated` events when the focus moves, but only if the node in question wasn't already updated as part of the tree update. This allows platform adapters to look for platform-specific property changes on the previously and newly focused nodes, again without duplicate events.
=> Raise node update events when focus changes

Cargo.lock, platforms/mac/Cargo.toml, platforms/mac/jni/Cargo.toml, schema/Cargo.toml, schema/src/lib.rs
This reduces build times when these features aren't needed.
=> Make serde and schemars optional

consumer/src/node.rs, consumer/src/tree.rs, platforms/windows/src/node.rs, platforms/windows/src/util.rs
This is useful for my egui integration, and will likely be useful in other toolkits as well.
=> Generate node name from `labelled_by` relationship

Cargo.lock, consumer/src/node.rs, platforms/windows/Cargo.toml, platforms/windows/src/node.rs, platforms/windows/src/util.rs
This also includes the necessary refactoring to support UIA patterns in a generic way.
=> Add UIA support for checkboxes

common/Cargo.toml, common/README.md, consumer/Cargo.toml, consumer/README.md, platforms/windows/Cargo.toml, platforms/windows/README.md
I'm not publishing the Mac crates for now.
The changes here are trivial enough that I'll go ahead and merge this, then publish the crates, once CI passes.
=> Prepare to publish on crates.io

consumer/src/node.rs
I use these in my AT-SPI adapter crate, and I think we will need them for Windows as well at some point.
=> Add more state related getters to accesskit_consumer::Node

Cargo.lock, common/Cargo.toml, consumer/Cargo.toml, platforms/windows/Cargo.toml
=> Prepare to publish v0.1.1

common/src/lib.rs, consumer/src/node.rs, platforms/windows/src/node.rs
This includes a partial implementation of the UIA selection item pattern.
Also, I previously misunderstood the Chromium radio group attribute. So that's fixed now, even though we're not yet using that info.
=> Add UIA support for radio buttons

common/Cargo.toml, consumer/Cargo.toml, platforms/windows/Cargo.toml
I'll merge this as soon as CI passes.
=> Prepare to publish v0.2.0

common/src/lib.rs, consumer/src/lib.rs, consumer/src/node.rs, consumer/src/tree.rs, platforms/windows/examples/hello_world.rs, platforms/windows/src/tests/simple.rs
This handles clients who use UUIDs for widget IDs.
=> Switch to NonZeroU128 for NodeIDs

common/src/lib.rs
Reverts AccessKit/accesskit#105
I messed up the conventional commit message again.
=> Revert "Various documentation fixes and improvements"

common/src/lib.rs
Re-merging #105 with the correct conventional commit message.
=> fix(common): Various documentation fixes and improvements

common/src/lib.rs, consumer/src/node.rs, platforms/windows/examples/hello_world.rs, platforms/windows/src/adapter.rs, platforms/windows/src/node.rs, platforms/windows/src/util.rs, platforms/winit/examples/simple.rs
This doesn't yet support the `live_atomic` and `live_relevant` fields, but it should be good enough for simple cases of announcing new and updated static text.
=> feat!: Basic live regions

README.md
The README needs to be updated to reflect the current state of the project.
fixes #155
=> docs: Update project README

Cargo.lock, platforms/macos/Cargo.toml, platforms/winit/Cargo.toml
At this point I don't care if release-please sets the version to something higher than 0.1.0, but I won't release it as 0.0.x.
=> fix(platforms/macos): Fix macOS crate version number

common/src/lib.rs
AccessKit's tree update code is somewhat more lenient than Chromium's seemed to be. I think the new docs are also clearer than what I took from Chromium.
=> docs: Fix outdated documentation for `TreeUpdate`

consumer/src/iterators.rs, consumer/src/node.rs
This makes it easier to implement accessibility in some GUI frameworks that build up widgets from simpler components.
=> feat: Automatically get button and link labels from descendants

platforms/macos/src/node.rs
macOS expects the text content of a static text control to be exposed as the value rather than the title. The immediate effect of this fix is that VoiceOver no longer adds "text" to the end of the text. This will probably become more important once we properly expose the labelled-by relation.
=> fix: Expose static text as the value rather than the title on macOS

consumer/src/node.rs
I originally implemented this correctly, but then I got in a hurry and let clippy automatically fix a warning without double-checking the fix. And since there was no test coverage for this method, the bug got through. So I added a test as well.
=> fix: Make `Node::filtered_parent` recursive as it was meant to be

Cargo.lock, platforms/unix/Cargo.toml
@DataTriny Please make sure this doesn't break anything in the Unix adapter. If not, let's get this out quickly.
=> fix: Update atspi dependency

common/src/lib.rs
=> fix: Set `repr(transparent)` on `NodeId`

platforms/macos/Cargo.toml
See https://github.com/rust-windowing/winit/pull/2739 for details.
=> Fix macOS leaks

platforms/unix/src/adapter.rs, platforms/unix/src/atspi/bus.rs, platforms/unix/src/atspi/interfaces/events.rs, platforms/unix/src/node.rs
This can't fully be tested using Orca at this time, I made sure that the events were properly fired with `dbus-monitor` though.
=> feat: Support live regions on Unix

Cargo.lock, common/Cargo.toml, common/src/lib.rs
=> fix: Bump pyo3; add `rename_all` attribute to enums

.github/workflows/ci.yml, deny.toml
=> ci: Add cargo-deny

bindings/c/CMakeLists.txt
This doesn't bring much to us, but it still contain a bunch of important bug fixes.
=> fix: Update Corrosion to 0.4.7

CONTRIBUTING.md, Cargo.lock, Cargo.toml, bindings/c/Cargo.toml, bindings/python/Cargo.toml, common/Cargo.toml, consumer/Cargo.toml, platforms/atspi-common/Cargo.toml, platforms/macos/Cargo.toml, platforms/unix/Cargo.toml, platforms/unix/src/context.rs, platforms/windows/Cargo.toml, platforms/winit/Cargo.toml
This is to allow updating to winit 1.30.
=> fix: Increase minimum supported Rust version to 1.70

consumer/src/tree.rs
Replace unwraps and asserts with descriptive panic messages.
=> Improve panic messages

consumer/src/tree.rs
This basically reverts #138. Comparing nodes is cheaper now than it was when we had a big struct with all possible properties. And I didn't end up moving to a node trait. On balance, it's now probably cheaper to compare nodes while processing the tree update than to do some kinds of comparisons in the platform adapter. But I kept the documentation change that I made in that PR, since what it says is still true; it's most efficient for tree updates to not include unchanged nodes.
Also, we no longer do a preliminary pass to collect updated nodes. This was necessary when we had to create detached nodes with some of the old state, but we're not doing that anymore.
=> fix: Go back to detecting unchanged nodes when processing tree updates

consumer/src/text.rs
@DataTriny discovered a way to cause a panic in AccessKit when moving in an egui multi-line edit. Apparently, the egui cursor can end up being outside the actual bounds of the text. I could fix this in egui, but I think it's better to make AccessKit resilient to broken implementations, when we can do so at little cost. So I implemented a fix in AccessKit instead.
To test this fix with egui, you'll need to cherry-pick this PR onto a local copy of the winit-0.29-backport branch.
=> fix: Clamp character indices when converting a text selection to a range

platforms/atspi-common/src/node.rs
This fixes the case where the window bounds aren't set at the adapter level, but the window's root object does have the bounds property. This currently happens in GTK 4 with Newton. Maybe I should extend the Newton AT protocol so the compositor can provide the window bounds, but this oculd also happen in other implementations with AT-SPI, and as always, we should make our code as resilient as practical.
This also handles the possible case where there are both kinds of bounds on the window; in that case, the adapter-level window size always constrains the node-level bounds, while the node-level bounds could possibly provide their own origin in window coordinates.
=> fix: Smarter calculation of AT-SPI extents for the window

common/src/lib.rs
My previous use of serde wasn't compatible with many data formats other than JSON, particularly those that serialize enum discriminants as integers rather than strings, and those that require the size of a map to be specified at the start of serialization.
To solve this, I've refactored the node structs internally. The dynamic properties are now stored in their own struct, and only that struct needs custom implementations of `Serialize` and `Deserialize`.
I also made serialization and deserialization more efficient by serializing the bitmasks for the actions and flags directly, rather than serializing the actions as a sequence and the flags as key/value pairs in the outer map.
The serialization to JSON, and similar formats, is now less human-friendly than it was. The dynamic properties …
=> refactor!: Optimize serialization and make it compatible with more data formats

common/src/lib.rs
Relates to https://github.com/AccessKit/accesskit-c/pull/8
We can't unfortunately use a macro when generating public types in the common crate: cbindgen will exclude them from the header file by default and telling it to expand the common crate is not possible AFAIK.
I've manually implemented a method similar to what the enumn crate would generate. The function which does the convertion from a mask to a list of actions doesn't rely on a manually provided upper bound, so the only place we would have to update if the enum change is the `Action::n` method. I don't think we can do better.
=> fix: Don't use a macro to generate Action debug helper function

consumer/src/iterators.rs, consumer/src/text.rs, platforms/atspi-common/src/node.rs, platforms/macos/src/node.rs, platforms/windows/src/node.rs
The CI failure is solved by #487.
=> fix: Remove unnecessary explicit lifetimes

Cargo.lock, common/Cargo.toml, common/src/lib.rs
This will allow us to support Python 3.13 for our Python bindings.
=> fix: Update pyo3 to 0.23

CONTRIBUTING.md, Cargo.toml
Reading the release notes, I don't think there are new features we can take advantage of.
=> fix: Update minimum supported Rust version to 1.77.2

Cargo.lock, platforms/atspi-common/Cargo.toml, platforms/atspi-common/src/adapter.rs, platforms/atspi-common/src/events.rs, platforms/atspi-common/src/node.rs, platforms/unix/Cargo.toml, platforms/unix/src/atspi/bus.rs, platforms/unix/src/atspi/object_id.rs, platforms/unix/src/context.rs
Also updates to latest versions of the atspi crates.
=> fix: Update zbus to 5.0

Cargo.lock
Part of #349 
- `cargo update core-graphics-types`
- `cargo update mio`
- `cargo update polling`
- `cargo update tempfile`
- `cargo update toml_edit`
=> chore: Update dependencies to remove some duplicates

Cargo.lock, platforms/windows/Cargo.toml, platforms/windows/examples/hello_world.rs, platforms/windows/src/node.rs, platforms/windows/src/subclass.rs, platforms/windows/src/tests/mod.rs, platforms/windows/src/text.rs, platforms/windows/src/util.rs
Recent changes in the `VARIANT` type make it easier to implement the `UIA_ControllerForPropertyId` property, which I need for dropdown.
=> fix: Update windows to 0.61

platforms/macos/src/event.rs
We need to raise appropriate events to let ATs know that nodes have been removed from the tree.
=> fix: Destroy nodes that become filtered out on macOS

consumer/src/tree.rs
=> fix: Eliminate incorrect removal of reparented nodes

consumer/src/filters.rs
I decided I should add at least one unit test for the new clipping behavior on the `consumer-scroll` branch, and I realized that we needed tests for the other filter behavior too.
=> test: Add unit tests for the common filters
